"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type BoundaryCheck={id:string;timestamp:string;decision:string;reason:string;providerConfigMode:string;providers:Array<{providerKey:string;enabled:boolean;requiredEnvKeys:string[];presentEnvKeys:string[];missingEnvKeys:string[];secretValuesStored:boolean;secretValuesExposed:boolean}>;boundaryChecks:Array<{name:string;passed:boolean;reason:string}>;networkCallPerformed:boolean;providerExecutionAllowed:boolean;realLlmCallAllowed:boolean;llmCallPerformed:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function ProviderConfigSecretBoundaryPage(){
 const [checks,setChecks]=useState<BoundaryCheck[]>([]); const [summary,setSummary]=useState<any>(null); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const res=await fetch("/api/provider-config-secret-boundary?limit=100",{cache:"no-store"}); const payload=await res.json(); if(!res.ok) throw new Error(payload?.error||"Boundary Checks konnten nicht geladen werden."); setChecks(Array.isArray(payload.boundaryChecks)?payload.boundaryChecks:[]); setSummary(payload.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createCheck(){ const res=await fetch("/api/provider-config-secret-boundary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({metadata:{trigger:"ui"}})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Boundary Check fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-config-secret-boundary" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fff7ed 0%,#f8fafc 100%)",borderColor:"#fdba74"}}><h1 className="section-title">Provider Config Secret Boundary</h1><p style={{lineHeight:1.6}}>Phase 23.0 bereitet Provider-Konfiguration und Secret Boundary vor. Es werden nur Presence-/Metadata-Checks gespeichert. Keine Secret-Werte, keine Provider-/Netzwerk-Aufrufe.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Boundary Check erstellen</h2><button className="primary-button" type="button" onClick={createCheck}>Provider Config Boundary prüfen</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Boundary Checks</h2>{checks.length===0 ? <p>Noch keine Boundary Checks.</p> : checks.map((check)=><article key={check.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{check.providerConfigMode}</strong> <span className="chip">{check.decision}</span></div><div className="helper-text"><code>{check.id}</code> · {check.timestamp}</div><p><strong>Reason:</strong> {check.reason}</p><p><strong>No secrets:</strong> {String(check.noSecretsIncluded)} · <strong>Network call:</strong> {String(check.networkCallPerformed)} · <strong>Provider execution:</strong> {String(check.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(check.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(check.llmCallPerformed)} · <strong>Execution:</strong> {String(check.executionAllowed)} · <strong>Tool:</strong> {String(check.toolExecutionAllowed)} · <strong>Agent:</strong> {String(check.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(check.dryRunOnly)}</p><h3>Providers</h3><ul>{check.providers?.map((provider)=><li key={provider.providerKey}><strong>{provider.providerKey}:</strong> enabled={String(provider.enabled)} · present=[{provider.presentEnvKeys.join(", ")}] · missing=[{provider.missingEnvKeys.join(", ")}] · secretValuesStored={String(provider.secretValuesStored)} · secretValuesExposed={String(provider.secretValuesExposed)}</li>)}</ul><h3>Boundary Checks</h3><ul>{check.boundaryChecks?.map((entry)=><li key={entry.name}><strong>{entry.name}:</strong> {String(entry.passed)} – {entry.reason}</li>)}</ul></article>)}</section></div></main>;
}
