"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Preflight={id:string;decision:string;timestamp:string;preflightMode:string};
type Contract={id:string;timestamp:string;decision:string;reason:string;contractMode:string;contractChecks:Array<{name:string;passed:boolean;reason:string}>;providerRequestContractPrepared:boolean;metadataOnly:boolean;provider:string;modelSelected:string;promptIncluded:boolean;promptRedactedPreviewIncluded:boolean;secretValuesIncluded:boolean;requestBodyIncluded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderRequestContractPage(){
 const [preflights,setPreflights]=useState<Preflight[]>([]); const [contracts,setContracts]=useState<Contract[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [pRes,cRes]=await Promise.all([fetch("/api/token-backed-provider-invocation-preflight?limit=100",{cache:"no-store"}),fetch("/api/provider-request-contract?limit=100",{cache:"no-store"})]); const p=await pRes.json(); const c=await cRes.json(); if(pRes.ok){ const list=Array.isArray(p.tokenBackedProviderInvocationPreflights)?p.tokenBackedProviderInvocationPreflights:[]; setPreflights(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!cRes.ok) throw new Error(c?.error||"Provider Request Contracts konnten nicht geladen werden."); setContracts(Array.isArray(c.providerRequestContracts)?c.providerRequestContracts:[]); setSummary(c.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function create(){ const res=await fetch("/api/provider-request-contract",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tokenBackedPreflightId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Provider Request Contract fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-request-contract" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fdf2f8 0%,#f8fafc 100%)",borderColor:"#f9a8d4"}}><h1 className="section-title">Provider Request Contract</h1><p style={{lineHeight:1.6}}>Phase 31.0 bereitet einen metadata-only Provider Request Contract vor. Kein Provider-/Netzwerk-Aufruf, kein Prompt, keine Secret-Werte, kein Request Body.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Provider Request Contract vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{preflights.map((item)=><option key={item.id} value={item.id}>{item.preflightMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={create} disabled={!selected}>Provider Request Contract vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Contracts</h2>{contracts.length===0?<p>Noch keine Provider Request Contracts.</p>:contracts.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.contractMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Contract:</strong> {String(item.providerRequestContractPrepared)} · <strong>Metadata-only:</strong> {String(item.metadataOnly)} · <strong>Provider:</strong> {item.provider} · <strong>Model:</strong> {item.modelSelected}</p><p><strong>Prompt:</strong> {String(item.promptIncluded)} · <strong>Redacted preview:</strong> {String(item.promptRedactedPreviewIncluded)} · <strong>Secrets:</strong> {String(item.secretValuesIncluded)} · <strong>Request body:</strong> {String(item.requestBodyIncluded)}</p><p><strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p><ul>{item.contractChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
