"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Plan={id:string;title:string;decision:string;actionType?:string};
type Rec={id:string;timestamp:string;title:string;decision:string;actionType?:string;recommendedNextAction:string;missingSafetyGates:string[];requiredConsentSteps:string[];requiredPolicySteps:string[];executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;llmRoutingPrepOnly:boolean;reason:string};
export default function MasterPlannerPage(){
 const [plans,setPlans]=useState<Plan[]>([]); const [recs,setRecs]=useState<Rec[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [pRes,rRes]=await Promise.all([fetch("/api/master-orchestrator?limit=100",{cache:"no-store"}),fetch("/api/master-planner?limit=100",{cache:"no-store"})]); const p=await pRes.json(); const r=await rRes.json(); if(pRes.ok){ const list=Array.isArray(p.plans)?p.plans:[]; setPlans(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!rRes.ok) throw new Error(r?.error||"Planner Recommendations konnten nicht geladen werden."); setRecs(Array.isArray(r.recommendations)?r.recommendations:[]); setSummary(r.summary||null); } catch(e){ setError(e instanceof Error?e.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function recommend(){ const res=await fetch("/api/master-planner",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orchestrationPlanId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Recommendation fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="master-planner" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#ecfeff 0%,#f8fafc 100%)",borderColor:"#67e8f9"}}><h1 className="section-title">Master Agent Planner</h1><p style={{lineHeight:1.6}}>Phase 16.0 bewertet Orchestration Plans und erzeugt sichere Next-Step-Empfehlungen. LLM-Routing-Prep, keine echte Ausführung.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Recommendation erzeugen</h2><select className="text-input" value={selected} onChange={(e)=>setSelected(e.target.value)}>{plans.map((plan)=><option key={plan.id} value={plan.id}>{plan.title} · {plan.decision} · {plan.id}</option>)}</select><button className="primary-button" type="button" onClick={recommend} disabled={!selected}>Planner Recommendation erzeugen</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Recommendations</h2>{recs.length===0 ? <p>Noch keine Planner Recommendations.</p> : recs.map((rec)=><article key={rec.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{rec.title}</strong> <span className="chip">{rec.decision}</span></div><div className="helper-text"><code>{rec.id}</code> · {rec.timestamp}</div><p><strong>Next:</strong> {rec.recommendedNextAction}</p><p><strong>Missing Gates:</strong> {rec.missingSafetyGates.length?rec.missingSafetyGates.join(", "):"none"}</p><p><strong>Consent:</strong> {rec.requiredConsentSteps.length?rec.requiredConsentSteps.join(", "):"none"}</p><p><strong>Policy:</strong> {rec.requiredPolicySteps.join(", ")}</p><p><strong>Execution:</strong> {String(rec.executionAllowed)} · <strong>Tool:</strong> {String(rec.toolExecutionAllowed)} · <strong>Agent:</strong> {String(rec.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(rec.dryRunOnly)} · <strong>LLM Routing Prep:</strong> {String(rec.llmRoutingPrepOnly)}</p></article>)}</section></div></main>;
}
