"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Gate={id:string;decision:string;timestamp:string;gateMode:string};
type Req={id:string;timestamp:string;decision:string;reason:string;requestMode:string;approvalRequest:any;providerCallPlan:any;operationalControls:any;requestChecks:Array<{name:string;passed:boolean;reason:string}>;networkCallPerformed:boolean;providerExecutionAllowed:boolean;realLlmCallAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function HumanApprovalTokenRequestPage(){
 const [gates,setGates]=useState<Gate[]>([]); const [requests,setRequests]=useState<Req[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [approvalReason,setApprovalReason]=useState("Manual approval requested for future real provider invocation. Token not issued automatically."); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [gRes,rRes]=await Promise.all([fetch("/api/controlled-real-provider-invocation-gate?limit=100",{cache:"no-store"}),fetch("/api/human-approval-token-request?limit=100",{cache:"no-store"})]); const g=await gRes.json(); const r=await rRes.json(); if(gRes.ok){ const list=Array.isArray(g.gates)?g.gates:[]; setGates(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!rRes.ok) throw new Error(r?.error||"Approval Token Requests konnten nicht geladen werden."); setRequests(Array.isArray(r.approvalTokenRequests)?r.approvalTokenRequests:[]); setSummary(r.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createRequest(){ const res=await fetch("/api/human-approval-token-request",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gateId:selected,approvalReason})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Approval Token Request fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="human-approval-token-request" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fff7ed 0%,#f8fafc 100%)",borderColor:"#fdba74"}}><h1 className="section-title">Human Approval Token Request</h1><p style={{lineHeight:1.6}}>Phase 27.0 erfasst einen expliziten Human Approval Token Request. Der Approval Token wird nicht automatisch erteilt. Kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Approval Token Request erfassen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{gates.map((gate)=><option key={gate.id} value={gate.id}>{gate.gateMode} · {gate.decision} · {gate.id}</option>)}</select><label>Approval Reason</label><textarea className="text-input" value={approvalReason} onChange={(ev)=>setApprovalReason(ev.target.value)} rows={3} /><button className="primary-button" type="button" onClick={createRequest} disabled={!selected}>Human Approval Token Request erfassen</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Approval Token Requests</h2>{requests.length===0 ? <p>Noch keine Approval Token Requests.</p> : requests.map((req)=><article key={req.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{req.requestMode}</strong> <span className="chip">{req.decision}</span></div><div className="helper-text"><code>{req.id}</code> · {req.timestamp}</div><p><strong>Reason:</strong> {req.reason}</p><p><strong>No secrets:</strong> {String(req.noSecretsIncluded)} · <strong>Network call:</strong> {String(req.networkCallPerformed)} · <strong>Provider execution:</strong> {String(req.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(req.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(req.llmCallPerformed)} · <strong>Dry-run:</strong> {String(req.dryRunOnly)}</p><h3>Approval Request</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(req.approvalRequest ?? {}, null, 2)}</pre><h3>Provider Call Plan</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(req.providerCallPlan ?? {}, null, 2)}</pre><ul>{req.requestChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
