"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Boundary={id:string;decision:string;timestamp:string};
type Adapter={id:string;decision:string;timestamp:string};
type Preflight={id:string;timestamp:string;decision:string;reason:string;readinessMode:string;readinessChecks:Array<{name:string;passed:boolean;reason:string}>;operationalDefaults:any;networkCallPerformed:boolean;providerExecutionAllowed:boolean;realLlmCallAllowed:boolean;llmCallPerformed:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function ProviderInvocationReadinessPreflightPage(){
 const [boundaries,setBoundaries]=useState<Boundary[]>([]); const [adapters,setAdapters]=useState<Adapter[]>([]); const [preflights,setPreflights]=useState<Preflight[]>([]); const [summary,setSummary]=useState<any>(null); const [boundaryId,setBoundaryId]=useState(""); const [adapterId,setAdapterId]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [bRes,aRes,pRes]=await Promise.all([fetch("/api/provider-config-secret-boundary?limit=100",{cache:"no-store"}),fetch("/api/provider-llm-adapter-stub?limit=100",{cache:"no-store"}),fetch("/api/provider-invocation-readiness-preflight?limit=100",{cache:"no-store"})]); const b=await bRes.json(); const a=await aRes.json(); const p=await pRes.json(); if(bRes.ok){ const list=Array.isArray(b.boundaryChecks)?b.boundaryChecks:[]; setBoundaries(list); if(!boundaryId && list[0]?.id) setBoundaryId(list[0].id); } if(aRes.ok){ const list=Array.isArray(a.adapterStubs)?a.adapterStubs:[]; setAdapters(list); if(!adapterId && list[0]?.id) setAdapterId(list[0].id); } if(!pRes.ok) throw new Error(p?.error||"Readiness Preflights konnten nicht geladen werden."); setPreflights(Array.isArray(p.preflights)?p.preflights:[]); setSummary(p.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createPreflight(){ const res=await fetch("/api/provider-invocation-readiness-preflight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({boundaryCheckId:boundaryId,adapterStubId:adapterId})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Preflight fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-invocation-readiness-preflight" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#eff6ff 0%,#f8fafc 100%)",borderColor:"#93c5fd"}}><h1 className="section-title">Provider Invocation Readiness Preflight</h1><p style={{lineHeight:1.6}}>Phase 24.0 bereitet einen Readiness Preflight für spätere Provider Invocation vor. Keine Secrets, keine Provider-/Netzwerk-Aufrufe und kein produktiver LLM-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Readiness Preflight erstellen</h2><label>Provider Config Boundary</label><select className="text-input" value={boundaryId} onChange={(ev)=>setBoundaryId(ev.target.value)}>{boundaries.map((b)=><option key={b.id} value={b.id}>{b.decision} · {b.id}</option>)}</select><label>Provider Adapter Stub</label><select className="text-input" value={adapterId} onChange={(ev)=>setAdapterId(ev.target.value)}>{adapters.map((a)=><option key={a.id} value={a.id}>{a.decision} · {a.id}</option>)}</select><button className="primary-button" type="button" onClick={createPreflight} disabled={!boundaryId || !adapterId}>Provider Invocation Readiness Preflight vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Readiness Preflights</h2>{preflights.length===0 ? <p>Noch keine Readiness Preflights.</p> : preflights.map((p)=><article key={p.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{p.readinessMode}</strong> <span className="chip">{p.decision}</span></div><div className="helper-text"><code>{p.id}</code> · {p.timestamp}</div><p><strong>Reason:</strong> {p.reason}</p><p><strong>No secrets:</strong> {String(p.noSecretsIncluded)} · <strong>Network call:</strong> {String(p.networkCallPerformed)} · <strong>Provider execution:</strong> {String(p.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(p.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(p.llmCallPerformed)} · <strong>Execution:</strong> {String(p.executionAllowed)} · <strong>Tool:</strong> {String(p.toolExecutionAllowed)} · <strong>Agent:</strong> {String(p.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(p.dryRunOnly)}</p><h3>Operational Defaults</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(p.operationalDefaults ?? {}, null, 2)}</pre><h3>Readiness Checks</h3><ul>{p.readinessChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
