"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Consent={id:string;decision:string;actionType?:string;timestamp:string;consentScope?:{approvalStatus:string}};
type Sim={id:string;timestamp:string;decision:string;actionType?:string;reason:string;simulatedDecision:string;realLlmCallAllowed:boolean;llmCallPerformed:boolean;consentRequired:boolean;humanApprovalRequired:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;decisionChecks:Array<{name:string;passed:boolean;reason:string}>};
export default function RealLlmConsentDecisionPage(){
 const [requests,setRequests]=useState<Consent[]>([]); const [sims,setSims]=useState<Sim[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [cRes,sRes]=await Promise.all([fetch("/api/real-llm-consent?limit=100",{cache:"no-store"}),fetch("/api/real-llm-consent-decision?limit=100",{cache:"no-store"})]); const c=await cRes.json(); const s=await sRes.json(); if(cRes.ok){ const list=Array.isArray(c.consentRequests)?c.consentRequests:[]; setRequests(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!sRes.ok) throw new Error(s?.error||"Consent Decision Simulations konnten nicht geladen werden."); setSims(Array.isArray(s.simulations)?s.simulations:[]); setSummary(s.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function simulate(){ const res=await fetch("/api/real-llm-consent-decision",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({consentRequestId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Simulation fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="real-llm-consent-decision" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fdf2f8 0%,#f8fafc 100%)",borderColor:"#f9a8d4"}}><h1 className="section-title">Real LLM Consent Decision</h1><p style={{lineHeight:1.6}}>Phase 20.1 simuliert die Consent-Entscheidung als Pending Review und schreibt Audit Events. Kein produktiver LLM-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Decision Simulation erstellen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{requests.map((req)=><option key={req.id} value={req.id}>{req.actionType || "real-llm-consent"} · {req.decision} · {req.consentScope?.approvalStatus || "pending"} · {req.id}</option>)}</select><button className="primary-button" type="button" onClick={simulate} disabled={!selected}>Consent Decision simulieren</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Decision Simulations</h2>{sims.length===0 ? <p>Noch keine Decision Simulations.</p> : sims.map((sim)=><article key={sim.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{sim.actionType || "real-llm-consent-decision"}</strong> <span className="chip">{sim.decision}</span></div><div className="helper-text"><code>{sim.id}</code> · {sim.timestamp}</div><p><strong>Reason:</strong> {sim.reason}</p><p><strong>Simulated decision:</strong> {sim.simulatedDecision}</p><p><strong>Real LLM allowed:</strong> {String(sim.realLlmCallAllowed)} · <strong>Consent:</strong> {String(sim.consentRequired)} · <strong>Human approval:</strong> {String(sim.humanApprovalRequired)} · <strong>LLM Call:</strong> {String(sim.llmCallPerformed)} · <strong>Execution:</strong> {String(sim.executionAllowed)} · <strong>Tool:</strong> {String(sim.toolExecutionAllowed)} · <strong>Agent:</strong> {String(sim.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(sim.dryRunOnly)}</p><ul>{sim.decisionChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
