"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Envelope={id:string;decision:string;timestamp:string;envelopeMode:string};
type Sim={id:string;timestamp:string;decision:string;reason:string;policyMode:string;policyChecks:Array<{name:string;passed:boolean;reason:string}>;providerRequestEnvelopeAssembled:boolean;metadataOnly:boolean;provider:string;modelSelected:string;envelopePayloadIncluded:boolean;promptPayloadIncluded:boolean;promptIncluded:boolean;secretValuesIncluded:boolean;requestBodyIncluded:boolean;sensitiveRequestBodyIncluded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function ProviderRequestEnvelopePolicyPage(){
 const [envelopes,setEnvelopes]=useState<Envelope[]>([]); const [sims,setSims]=useState<Sim[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [eRes,sRes]=await Promise.all([fetch("/api/provider-request-envelope?limit=100",{cache:"no-store"}),fetch("/api/provider-request-envelope-policy?limit=100",{cache:"no-store"})]); const e=await eRes.json(); const s=await sRes.json(); if(eRes.ok){ const list=Array.isArray(e.providerRequestEnvelopes)?e.providerRequestEnvelopes:[]; setEnvelopes(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!sRes.ok) throw new Error(s?.error||"Policy Simulations konnten nicht geladen werden."); setSims(Array.isArray(s.simulations)?s.simulations:[]); setSummary(s.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function simulate(){ const res=await fetch("/api/provider-request-envelope-policy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerRequestEnvelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Policy Simulation fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-request-envelope-policy" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#faf5ff 0%,#f8fafc 100%)",borderColor:"#d8b4fe"}}><h1 className="section-title">Provider Request Envelope Policy</h1><p style={{lineHeight:1.6}}>Phase 32.1 simuliert Policy Checks für Provider Request Envelopes. Envelope bleibt metadata-only. Kein Provider-/Netzwerk-Aufruf, kein Prompt Payload, keine Secret-Werte, kein sensibler Request Body.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Policy Simulation erstellen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{envelopes.map((item)=><option key={item.id} value={item.id}>{item.envelopeMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={simulate} disabled={!selected}>Provider Request Envelope Policy simulieren</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Policy Simulations</h2>{sims.length===0?<p>Noch keine Policy Simulations.</p>:sims.map((sim)=><article key={sim.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{sim.policyMode}</strong> <span className="chip">{sim.decision}</span></div><div className="helper-text"><code>{sim.id}</code> · {sim.timestamp}</div><p><strong>Reason:</strong> {sim.reason}</p><p><strong>Assembled:</strong> {String(sim.providerRequestEnvelopeAssembled)} · <strong>Metadata-only:</strong> {String(sim.metadataOnly)} · <strong>Provider:</strong> {sim.provider} · <strong>Model:</strong> {sim.modelSelected}</p><p><strong>Envelope payload:</strong> {String(sim.envelopePayloadIncluded)} · <strong>Prompt payload:</strong> {String(sim.promptPayloadIncluded)} · <strong>Secrets:</strong> {String(sim.secretValuesIncluded)} · <strong>Request body:</strong> {String(sim.requestBodyIncluded)} · <strong>Sensitive body:</strong> {String(sim.sensitiveRequestBodyIncluded)}</p><p><strong>Network call:</strong> {String(sim.networkCallPerformed)} · <strong>Provider execution:</strong> {String(sim.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(sim.llmCallPerformed)} · <strong>Dry-run:</strong> {String(sim.dryRunOnly)}</p><ul>{sim.policyChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
