"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type TranscriptEnvelope={id:string;decision:string;timestamp:string;transcriptMode:string};
type ReleaseCandidateEnvelope={id:string;timestamp:string;decision:string;reason:string;envelopeMode:string;providerDispatchReleaseCandidateEnvelopePrepared:boolean;releaseCandidateEnvelopePrepared:boolean;releaseCandidateEnvelopePersisted:boolean;releaseCandidateReadyForHumanReview:boolean;releaseCandidateApproved:boolean;releaseCandidateExecuted:boolean;releaseCandidateContainsProviderResponse:boolean;releaseCandidateContainsPromptPayload:boolean;releaseCandidateContainsSecrets:boolean;commandEnvelopeExecuted:boolean;executionGateOpen:boolean;finalDispatchAllowed:boolean;networkCallAllowed:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchReleaseCandidateEnvelopePage(){
 const [transcripts,setTranscripts]=useState<TranscriptEnvelope[]>([]); const [candidates,setCandidates]=useState<ReleaseCandidateEnvelope[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [tRes,cRes]=await Promise.all([fetch("/api/provider-dispatch-transcript-envelope?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-release-candidate-envelope?limit=100",{cache:"no-store"})]); const t=await tRes.json(); const c=await cRes.json(); if(tRes.ok){ const list=Array.isArray(t.providerDispatchTranscriptEnvelopes)?t.providerDispatchTranscriptEnvelopes:[]; setTranscripts(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!cRes.ok) throw new Error(c?.error||"Release Candidate Envelopes konnten nicht geladen werden."); setCandidates(Array.isArray(c.providerDispatchReleaseCandidateEnvelopes)?c.providerDispatchReleaseCandidateEnvelopes:[]); setSummary(c.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createEnvelope(){ const res=await fetch("/api/provider-dispatch-release-candidate-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerDispatchTranscriptEnvelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Release Candidate Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-release-candidate-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f8fafc 0%,#eef2ff 100%)",borderColor:"#c7d2fe"}}><h1 className="section-title">Provider Dispatch Release Candidate Envelope</h1><p style={{lineHeight:1.6}}>Phase 40.0 bereitet ein Provider Dispatch Release Candidate Envelope vor. Es ist nur bereit für Human Review, nicht approved und nicht ausgeführt. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Release Candidate Envelope vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{transcripts.map((item)=><option key={item.id} value={item.id}>{item.transcriptMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>Provider Dispatch Release Candidate Envelope vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Release Candidate Envelopes</h2>{candidates.length===0?<p>Noch keine Release Candidate Envelopes.</p>:candidates.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.envelopeMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Prepared:</strong> {String(item.providerDispatchReleaseCandidateEnvelopePrepared)} · <strong>Persisted:</strong> {String(item.releaseCandidateEnvelopePersisted)} · <strong>Human review:</strong> {String(item.releaseCandidateReadyForHumanReview)} · <strong>Approved:</strong> {String(item.releaseCandidateApproved)} · <strong>Executed:</strong> {String(item.releaseCandidateExecuted)}</p><p><strong>Provider response:</strong> {String(item.releaseCandidateContainsProviderResponse)} · <strong>Prompt payload:</strong> {String(item.releaseCandidateContainsPromptPayload)} · <strong>Secrets:</strong> {String(item.releaseCandidateContainsSecrets)}</p><p><strong>Command executed:</strong> {String(item.commandEnvelopeExecuted)} · <strong>Gate open:</strong> {String(item.executionGateOpen)} · <strong>Final dispatch allowed:</strong> {String(item.finalDispatchAllowed)} · <strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
