"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type ApiState={summary?:any;items?:any[]};
async function fetchJson(url:string){ const res=await fetch(url,{cache:"no-store"}); const payload=await res.json(); if(!res.ok) throw new Error(payload?.error||url); return payload; }
export default function MasterPlannerDashboardPage(){
 const [orchestrations,setOrchestrations]=useState<ApiState>({}); const [recommendations,setRecommendations]=useState<ApiState>({}); const [policy,setPolicy]=useState<ApiState>({}); const [audit,setAudit]=useState<ApiState>({}); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [o,r,p,a]=await Promise.all([fetchJson("/api/master-orchestrator?limit=200"),fetchJson("/api/master-planner?limit=200"),fetchJson("/api/master-planner-policy?limit=200"),fetchJson("/api/governance-audit?limit=200")]); setOrchestrations({summary:o.summary,items:o.plans||[]}); setRecommendations({summary:r.summary,items:r.recommendations||[]}); setPolicy({summary:p.summary,items:p.simulations||[]}); setAudit({summary:a.summary,items:a.events||[]}); } catch(e){ setError(e instanceof Error?e.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 const cards=[ ["Orchestration Plans",orchestrations,"/master-orchestrator"], ["Planner Recommendations",recommendations,"/master-planner"], ["Planner Policy Simulations",policy,"/master-planner-policy"], ["Governance Audit",audit,"/governance-audit"] ] as const;
 return <main className="page-wrap"><UnifiedNavigation active="master-planner-dashboard" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#ecfeff 0%,#f8fafc 100%)",borderColor:"#67e8f9"}}><h1 className="section-title">Master Planner Dashboard</h1><p style={{lineHeight:1.6}}>Phase 16.2 fasst Orchestration Plans, Planner Recommendations, Planner Policy Simulationen und Audit zusammen. Weiterhin nur LLM-Routing-Prep, keine echte Ausführung.</p><button className="secondary-button" type="button" onClick={load}>Dashboard aktualisieren</button></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Planner Übersicht</h2><div className="metrics-grid">{cards.map(([title,state,href])=><a className="metric-card" href={href} key={title} style={{textDecoration:"none",color:"inherit"}}><span className="metric-label">{title}</span><strong className="metric-value">{state.items?.length ?? 0}</strong><pre style={{whiteSpace:"pre-wrap",marginTop:8}}>{JSON.stringify(state.summary ?? {}, null, 2)}</pre></a>)}</div></section><section className="panel-card"><h2>Safety Invariants</h2><ul><li>executionAllowed=false</li><li>toolExecutionAllowed=false</li><li>agentExecutionAllowed=false</li><li>dryRunOnly=true</li><li>llmRoutingPrepOnly=true</li><li>Keine echte Tool- oder Agent-Ausführung.</li></ul></section></div></main>;
}
