"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Env={id:string;decision:string;actionType?:string;timestamp:string};
type Stub={id:string;timestamp:string;decision:string;actionType?:string;reason:string;adapterMode:string;realLlmCallAllowed:boolean;llmCallPerformed:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;adapterChecks:Array<{name:string;passed:boolean;reason:string}>;providerRequestPreview:any;adapterResponsePreview:any};
export default function ProviderAgnosticLlmAdapterStubPage(){
 const [envelopes,setEnvelopes]=useState<Env[]>([]); const [stubs,setStubs]=useState<Stub[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [eRes,sRes]=await Promise.all([fetch("/api/approved-real-llm-invocation-envelope?limit=100",{cache:"no-store"}),fetch("/api/provider-llm-adapter-stub?limit=100",{cache:"no-store"})]); const e=await eRes.json(); const s=await sRes.json(); if(eRes.ok){ const list=Array.isArray(e.invocationEnvelopes)?e.invocationEnvelopes:[]; setEnvelopes(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!sRes.ok) throw new Error(s?.error||"Adapter Stubs konnten nicht geladen werden."); setStubs(Array.isArray(s.adapterStubs)?s.adapterStubs:[]); setSummary(s.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createStub(){ const res=await fetch("/api/provider-llm-adapter-stub",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({invocationEnvelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Adapter Stub fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-llm-adapter-stub" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f0fdf4 0%,#f8fafc 100%)",borderColor:"#86efac"}}><h1 className="section-title">Provider-Agnostic LLM Adapter Stub</h1><p style={{lineHeight:1.6}}>Phase 22.0 bereitet einen provider-agnostischen LLM Invocation Adapter Stub vor. Kein Netzwerk-/Provider-Aufruf, kein produktiver LLM-Aufruf und keine Tool-/Agent-Ausführung.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Adapter Stub vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{envelopes.map((env)=><option key={env.id} value={env.id}>{env.actionType || "invocation-envelope"} · {env.decision} · {env.id}</option>)}</select><button className="primary-button" type="button" onClick={createStub} disabled={!selected}>Provider Adapter Stub vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Adapter Stubs</h2>{stubs.length===0 ? <p>Noch keine Adapter Stubs.</p> : stubs.map((stub)=><article key={stub.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{stub.actionType || "provider-adapter-stub"}</strong> <span className="chip">{stub.decision}</span></div><div className="helper-text"><code>{stub.id}</code> · {stub.timestamp}</div><p><strong>Reason:</strong> {stub.reason}</p><p><strong>Mode:</strong> {stub.adapterMode}</p><p><strong>Network call:</strong> {String(stub.networkCallPerformed)} · <strong>Provider execution:</strong> {String(stub.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(stub.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(stub.llmCallPerformed)} · <strong>Execution:</strong> {String(stub.executionAllowed)} · <strong>Tool:</strong> {String(stub.toolExecutionAllowed)} · <strong>Agent:</strong> {String(stub.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(stub.dryRunOnly)}</p><h3>Adapter Checks</h3><ul>{stub.adapterChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul><h3>Provider Request Preview</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(stub.providerRequestPreview ?? {}, null, 2)}</pre><h3>Adapter Response Preview</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(stub.adapterResponsePreview ?? {}, null, 2)}</pre></article>)}</section></div></main>;
}
