"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Rec={id:string;title:string;decision:string;actionType?:string};
type Env={id:string;timestamp:string;decision:string;actionType?:string;reason:string;sanitizedContext:any;explainerPrompt:string;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;llmRoutingPrepOnly:boolean;noSecretsIncluded:boolean};
export default function ControlledLlmRoutingPage(){
 const [recs,setRecs]=useState<Rec[]>([]); const [envelopes,setEnvelopes]=useState<Env[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [rRes,eRes]=await Promise.all([fetch("/api/master-planner?limit=100",{cache:"no-store"}),fetch("/api/llm-routing-envelope?limit=100",{cache:"no-store"})]); const r=await rRes.json(); const e=await eRes.json(); if(rRes.ok){ const list=Array.isArray(r.recommendations)?r.recommendations:[]; setRecs(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!eRes.ok) throw new Error(e?.error||"LLM Routing Envelopes konnten nicht geladen werden."); setEnvelopes(Array.isArray(e.envelopes)?e.envelopes:[]); setSummary(e.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createEnvelope(){ const res=await fetch("/api/llm-routing-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recommendationId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="llm-routing-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f0f9ff 0%,#f8fafc 100%)",borderColor:"#7dd3fc"}}><h1 className="section-title">Controlled LLM Routing Envelope</h1><p style={{lineHeight:1.6}}>Phase 17.0 erzeugt einen sanitisierten Routing-Envelope für Planner Recommendations. Kein LLM-Aufruf, keine echte Ausführung, nur Empfehlung/Erklärung.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Envelope erstellen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{recs.map((rec)=><option key={rec.id} value={rec.id}>{rec.title} · {rec.decision} · {rec.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>LLM Routing Envelope erzeugen</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Routing Envelopes</h2>{envelopes.length===0 ? <p>Noch keine LLM Routing Envelopes.</p> : envelopes.map((env)=><article key={env.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{env.actionType || "planner"}</strong> <span className="chip">{env.decision}</span></div><div className="helper-text"><code>{env.id}</code> · {env.timestamp}</div><p><strong>Reason:</strong> {env.reason}</p><p><strong>Execution:</strong> {String(env.executionAllowed)} · <strong>Tool:</strong> {String(env.toolExecutionAllowed)} · <strong>Agent:</strong> {String(env.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(env.dryRunOnly)} · <strong>LLM Routing Prep:</strong> {String(env.llmRoutingPrepOnly)} · <strong>No Secrets:</strong> {String(env.noSecretsIncluded)}</p><h3>Sanitized Context</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(env.sanitizedContext, null, 2)}</pre><h3>Explainer Prompt</h3><pre style={{whiteSpace:"pre-wrap"}}>{env.explainerPrompt}</pre></article>)}</section></div></main>;
}
