"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Preflight={id:string;decision:string;timestamp:string;preflightMode:string};
type Gate={id:string;timestamp:string;decision:string;reason:string;gateMode:string;providerDispatchExecutionGatePrepared:boolean;executionGateOpen:boolean;finalDispatchAllowed:boolean;networkCallAllowed:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchExecutionGatePage(){
 const [preflights,setPreflights]=useState<Preflight[]>([]); const [gates,setGates]=useState<Gate[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [pRes,gRes]=await Promise.all([fetch("/api/provider-dispatch-final-preflight?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-execution-gate?limit=100",{cache:"no-store"})]); const p=await pRes.json(); const g=await gRes.json(); if(pRes.ok){ const list=Array.isArray(p.providerDispatchFinalPreflights)?p.providerDispatchFinalPreflights:[]; setPreflights(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!gRes.ok) throw new Error(g?.error||"Execution Gates konnten nicht geladen werden."); setGates(Array.isArray(g.providerDispatchExecutionGates)?g.providerDispatchExecutionGates:[]); setSummary(g.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createGate(){ const res=await fetch("/api/provider-dispatch-execution-gate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerDispatchFinalPreflightId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Execution Gate fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-execution-gate" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f8fafc 0%,#eef2ff 100%)",borderColor:"#c7d2fe"}}><h1 className="section-title">Provider Dispatch Execution Gate</h1><p style={{lineHeight:1.6}}>Phase 36.0 bereitet das Provider Dispatch Execution Gate vor. Execution Gate bleibt geschlossen. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Execution Gate vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{preflights.map((item)=><option key={item.id} value={item.id}>{item.preflightMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createGate} disabled={!selected}>Provider Dispatch Execution Gate vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Execution Gates</h2>{gates.length===0?<p>Noch keine Execution Gates.</p>:gates.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.gateMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Prepared:</strong> {String(item.providerDispatchExecutionGatePrepared)} · <strong>Gate open:</strong> {String(item.executionGateOpen)} · <strong>Final dispatch allowed:</strong> {String(item.finalDispatchAllowed)} · <strong>Network allowed:</strong> {String(item.networkCallAllowed)}</p><p><strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
