"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Contract={id:string;decision:string;timestamp:string;contractMode:string};
type Envelope={id:string;timestamp:string;decision:string;reason:string;envelopeMode:string;envelopeChecks:Array<{name:string;passed:boolean;reason:string}>;providerRequestEnvelopeAssembled:boolean;metadataOnly:boolean;provider:string;modelSelected:string;envelopePayloadIncluded:boolean;promptPayloadIncluded:boolean;promptIncluded:boolean;secretValuesIncluded:boolean;requestBodyIncluded:boolean;sensitiveRequestBodyIncluded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderRequestEnvelopePage(){
 const [contracts,setContracts]=useState<Contract[]>([]); const [envelopes,setEnvelopes]=useState<Envelope[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [cRes,eRes]=await Promise.all([fetch("/api/provider-request-contract?limit=100",{cache:"no-store"}),fetch("/api/provider-request-envelope?limit=100",{cache:"no-store"})]); const c=await cRes.json(); const e=await eRes.json(); if(cRes.ok){ const list=Array.isArray(c.providerRequestContracts)?c.providerRequestContracts:[]; setContracts(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!eRes.ok) throw new Error(e?.error||"Provider Request Envelopes konnten nicht geladen werden."); setEnvelopes(Array.isArray(e.providerRequestEnvelopes)?e.providerRequestEnvelopes:[]); setSummary(e.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function create(){ const res=await fetch("/api/provider-request-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerRequestContractId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Provider Request Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-request-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#eff6ff 0%,#f8fafc 100%)",borderColor:"#93c5fd"}}><h1 className="section-title">Provider Request Envelope</h1><p style={{lineHeight:1.6}}>Phase 32.0 assembliert einen metadata-only Provider Request Envelope. Kein Provider-/Netzwerk-Aufruf, kein Prompt Payload, keine Secret-Werte, kein sensibler Request Body.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Provider Request Envelope assemblieren</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{contracts.map((item)=><option key={item.id} value={item.id}>{item.contractMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={create} disabled={!selected}>Provider Request Envelope assemblieren</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Envelopes</h2>{envelopes.length===0?<p>Noch keine Provider Request Envelopes.</p>:envelopes.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.envelopeMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Envelope:</strong> {String(item.providerRequestEnvelopeAssembled)} · <strong>Metadata-only:</strong> {String(item.metadataOnly)} · <strong>Provider:</strong> {item.provider} · <strong>Model:</strong> {item.modelSelected}</p><p><strong>Envelope payload:</strong> {String(item.envelopePayloadIncluded)} · <strong>Prompt payload:</strong> {String(item.promptPayloadIncluded)} · <strong>Prompt:</strong> {String(item.promptIncluded)} · <strong>Secrets:</strong> {String(item.secretValuesIncluded)} · <strong>Request body:</strong> {String(item.requestBodyIncluded)} · <strong>Sensitive body:</strong> {String(item.sensitiveRequestBodyIncluded)}</p><p><strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p><ul>{item.envelopeChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
