"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Issuance={id:string;decision:string;timestamp:string;issuanceGateMode:string};
type Gate={id:string;decision:string;timestamp:string;activationGateMode:string;activationChecks:Array<{name:string;passed:boolean;reason:string}>;approvalTokenIssued:boolean;tokenActivationPrepared:boolean;tokenActive:boolean;humanApproved:boolean;activationIntentRecorded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean;reason:string};
export default function ApprovalTokenActivationGatePage(){
 const [issuance,setIssuance]=useState<Issuance[]>([]); const [gates,setGates]=useState<Gate[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [intent,setIntent]=useState(false); const [error,setError]=useState<string|null>(null);
 async function load(){setError(null);try{const [iRes,gRes]=await Promise.all([fetch("/api/approval-token-issuance-gate?limit=100",{cache:"no-store"}),fetch("/api/approval-token-activation-gate?limit=100",{cache:"no-store"})]);const i=await iRes.json();const g=await gRes.json();if(iRes.ok){const list=Array.isArray(i.approvalTokenIssuanceGates)?i.approvalTokenIssuanceGates:[];setIssuance(list);if(!selected&&list[0]?.id)setSelected(list[0].id);}if(!gRes.ok)throw new Error(g?.error||"Activation Gates konnten nicht geladen werden.");setGates(Array.isArray(g.approvalTokenActivationGates)?g.approvalTokenActivationGates:[]);setSummary(g.summary||null);}catch(err){setError(err instanceof Error?err.message:"Unbekannter Fehler");}}
 useEffect(()=>{load();},[]);
 async function create(){const res=await fetch("/api/approval-token-activation-gate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({issuanceGateId:selected,activationIntentRecorded:intent})});if(!res.ok){const p=await res.json();setError(p?.error||"Activation Gate fehlgeschlagen");}await load();}
 return <main className="page-wrap"><UnifiedNavigation active="approval-token-activation-gate" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fff7ed 0%,#f8fafc 100%)",borderColor:"#fdba74"}}><h1 className="section-title">Approval Token Activation Gate</h1><p style={{lineHeight:1.6}}>Phase 29.0 bereitet eine separate Token-Aktivierung vor. Token bleibt nicht aktiv. Kein Provider-/Netzwerk-Aufruf.</p></section>{error?<section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section>:null}<section className="panel-card"><h2>Activation Gate vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{issuance.map((item)=><option key={item.id} value={item.id}>{item.issuanceGateMode} · {item.decision} · {item.id}</option>)}</select><label style={{display:"flex",gap:8,alignItems:"center",margin:"10px 0"}}><input type="checkbox" checked={intent} onChange={(ev)=>setIntent(ev.target.checked)} /> Explicit activation intent recorded</label><button className="primary-button" type="button" onClick={create} disabled={!selected}>Approval Token Activation Gate vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Activation Gates</h2>{gates.length===0?<p>Noch keine Activation Gates.</p>:gates.map((gate)=><article key={gate.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{gate.activationGateMode}</strong> <span className="chip">{gate.decision}</span></div><div className="helper-text"><code>{gate.id}</code> · {gate.timestamp}</div><p><strong>Reason:</strong> {gate.reason}</p><p><strong>Issued:</strong> {String(gate.approvalTokenIssued)} · <strong>Activation prepared:</strong> {String(gate.tokenActivationPrepared)} · <strong>Token active:</strong> {String(gate.tokenActive)} · <strong>Human approved:</strong> {String(gate.humanApproved)} · <strong>Activation intent:</strong> {String(gate.activationIntentRecorded)}</p><p><strong>Network call:</strong> {String(gate.networkCallPerformed)} · <strong>Provider execution:</strong> {String(gate.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(gate.llmCallPerformed)} · <strong>Dry-run:</strong> {String(gate.dryRunOnly)}</p><ul>{gate.activationChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
