"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type Receipt = { id: string; decision: string; timestamp: string; receiptMode: string };
export default function ProviderDispatchHumanApprovalTokenIssuanceReceiptPolicyPage() {
  const [receipts, setReceipts] = useState<Receipt[]>([]); const [selected, setSelected] = useState(""); const [result, setResult] = useState<unknown>(null); const [error, setError] = useState<string | null>(null);
  async function load() { try { const res = await fetch("/api/provider-dispatch-human-approval-token-issuance-receipt?limit=100", { cache: "no-store" }); const body = await res.json(); if (res.ok) { const list = Array.isArray(body.providerDispatchHumanApprovalTokenIssuanceReceipts) ? body.providerDispatchHumanApprovalTokenIssuanceReceipts : []; setReceipts(list); if (!selected && list[0]?.id) setSelected(list[0].id); } } catch {} }
  useEffect(() => { load(); }, []);
  async function runSimulation() { setError(null); const res = await fetch("/api/provider-dispatch-human-approval-token-issuance-receipt-policy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceReceiptId: selected }) }); const data = await res.json(); if (!res.ok) { setError(data?.error || "Policy Simulation fehlgeschlagen"); return; } setResult(data.simulation); }
  return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-human-approval-token-issuance-receipt-policy" /><div className="page-shell"><section className="hero-card"><h1 className="section-title">Provider Dispatch Human Approval Token Issuance Receipt Policy</h1><p style={{ lineHeight: 1.6 }}>Phase 47.1 simuliert die Receipt Policy audit-only. Der Receipt bleibt receipt-only und review-only. Kein Token wird issued, aktiviert oder konsumiert. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{ borderColor: "#fecaca", background: "#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Receipt Policy simulieren</h2><select className="text-input" value={selected} onChange={(ev) => setSelected(ev.target.value)}>{receipts.map((item) => <option key={item.id} value={item.id}>{item.receiptMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={runSimulation}>Receipt Policy simulieren</button></section><section className="panel-card"><h2>Safety Invariants</h2><ul><li>providerDispatchHumanApprovalTokenIssuanceReceiptRecorded=true</li><li>humanApprovalTokenIssuanceReceiptPrepared=true</li><li>humanApprovalTokenIssuanceReceiptPersisted=true</li><li>humanApprovalTokenIssued=false</li><li>humanApprovalTokenActivated=false</li><li>humanApprovalTokenConsumed=false</li><li>approvalCandidateApproved=false</li><li>approvalCandidateExecuted=false</li><li>networkCallAllowed=false</li><li>networkCallPerformed=false</li><li>providerExecutionAllowed=false</li><li>llmCallPerformed=false</li><li>dryRunOnly=true</li></ul></section>{result ? <section className="panel-card"><h2>Simulation Result</h2><pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(result, null, 2)}</pre></section> : null}</div></main>;
}
