"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type ApiState={summary?:any;items?:any[];error?:string};
async function fetchJson(url:string){ const res=await fetch(url,{cache:"no-store"}); const payload=await res.json(); if(!res.ok) throw new Error(payload?.error||url); return payload; }
export default function MasterOrchestratorDashboardPage(){
 const [actions,setActions]=useState<ApiState>({}); const [plans,setPlans]=useState<ApiState>({}); const [policy,setPolicy]=useState<ApiState>({}); const [audit,setAudit]=useState<ApiState>({}); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [a,p,s,g]=await Promise.all([fetchJson("/api/cockpit-actions?limit=200"),fetchJson("/api/master-orchestrator?limit=200"),fetchJson("/api/master-orchestrator-policy?limit=200"),fetchJson("/api/governance-audit?limit=200")]); setActions({summary:a.summary,items:a.plans||[]}); setPlans({summary:p.summary,items:p.plans||[]}); setPolicy({summary:s.summary,items:s.simulations||[]}); setAudit({summary:g.summary,items:g.events||[]}); } catch(e){ setError(e instanceof Error?e.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 const cards=[ ["Cockpit Actions",actions,"/cockpit-actions"], ["Orchestration Plans",plans,"/master-orchestrator"], ["Policy Simulations",policy,"/master-orchestrator-policy"], ["Governance Audit",audit,"/governance-audit"] ] as const;
 return <main className="page-wrap"><UnifiedNavigation active="master-orchestrator-dashboard" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#eef2ff 0%,#f8fafc 100%)",borderColor:"#a5b4fc"}}><h1 className="section-title">Master Orchestrator Dashboard</h1><p style={{lineHeight:1.6}}>Phase 15.2 fasst Cockpit Actions, Orchestration Plans, Policy Simulationen und Audit zusammen. Keine echte Tool- oder Agent-Ausführung.</p><button className="secondary-button" type="button" onClick={load}>Dashboard aktualisieren</button></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Orchestrator Übersicht</h2><div className="metrics-grid">{cards.map(([title,state,href])=><a className="metric-card" href={href} key={title} style={{textDecoration:"none",color:"inherit"}}><span className="metric-label">{title}</span><strong className="metric-value">{state.items?.length ?? 0}</strong><pre style={{whiteSpace:"pre-wrap",marginTop:8}}>{JSON.stringify(state.summary ?? {}, null, 2)}</pre></a>)}</div></section><section className="panel-card"><h2>Safety Invariants</h2><ul><li>executionAllowed=false</li><li>toolExecutionAllowed=false</li><li>agentExecutionAllowed=false</li><li>dryRunOnly=true</li><li>Consent/Policy/Audit bleiben vor echter Ausführung verpflichtend.</li></ul></section></div></main>;
}
