"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Env={id:string;decision:string;timestamp:string;simulationMode:string};
type Gate={id:string;timestamp:string;decision:string;reason:string;gateMode:string;approvalState:any;providerCallPlan:any;operationalControls:any;gateChecks:Array<{name:string;passed:boolean;reason:string}>;networkCallPerformed:boolean;providerExecutionAllowed:boolean;realLlmCallAllowed:boolean;llmCallPerformed:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function ControlledRealProviderInvocationGatePage(){
 const [envelopes,setEnvelopes]=useState<Env[]>([]); const [gates,setGates]=useState<Gate[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [eRes,gRes]=await Promise.all([fetch("/api/controlled-provider-invocation-simulation-envelope?limit=100",{cache:"no-store"}),fetch("/api/controlled-real-provider-invocation-gate?limit=100",{cache:"no-store"})]); const e=await eRes.json(); const g=await gRes.json(); if(eRes.ok){ const list=Array.isArray(e.simulationEnvelopes)?e.simulationEnvelopes:[]; setEnvelopes(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!gRes.ok) throw new Error(g?.error||"Gates konnten nicht geladen werden."); setGates(Array.isArray(g.gates)?g.gates:[]); setSummary(g.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createGate(){ const res=await fetch("/api/controlled-real-provider-invocation-gate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({simulationEnvelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Gate fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="controlled-real-provider-invocation-gate" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fff1f2 0%,#f8fafc 100%)",borderColor:"#fda4af"}}><h1 className="section-title">Controlled Real Provider Invocation Gate</h1><p style={{lineHeight:1.6}}>Phase 26.0 bereitet ein Gate für echte Provider Invocation vor. Kein automatischer Netzwerk-/Provider-Aufruf. Explizite Human Approval ist zwingend.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Gate vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{envelopes.map((env)=><option key={env.id} value={env.id}>{env.simulationMode} · {env.decision} · {env.id}</option>)}</select><button className="primary-button" type="button" onClick={createGate} disabled={!selected}>Controlled Real Provider Invocation Gate vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Gates</h2>{gates.length===0 ? <p>Noch keine Gates.</p> : gates.map((gate)=><article key={gate.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{gate.gateMode}</strong> <span className="chip">{gate.decision}</span></div><div className="helper-text"><code>{gate.id}</code> · {gate.timestamp}</div><p><strong>Reason:</strong> {gate.reason}</p><p><strong>No secrets:</strong> {String(gate.noSecretsIncluded)} · <strong>Network call:</strong> {String(gate.networkCallPerformed)} · <strong>Provider execution:</strong> {String(gate.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(gate.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(gate.llmCallPerformed)} · <strong>Execution:</strong> {String(gate.executionAllowed)} · <strong>Tool:</strong> {String(gate.toolExecutionAllowed)} · <strong>Agent:</strong> {String(gate.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(gate.dryRunOnly)}</p><h3>Approval State</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(gate.approvalState ?? {}, null, 2)}</pre><h3>Provider Call Plan</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(gate.providerCallPlan ?? {}, null, 2)}</pre><h3>Operational Controls</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(gate.operationalControls ?? {}, null, 2)}</pre><ul>{gate.gateChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
