"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Resp={id:string;decision:string;actionType?:string;timestamp:string};
type Gate={id:string;timestamp:string;decision:string;actionType?:string;reason:string;sanitizedPromptPreview:string;realLlmCallAllowed:boolean;policyGateRequired:boolean;llmCallPerformed:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;gateChecks:Array<{name:string;passed:boolean;reason:string}>};
export default function RealLlmCallGatePage(){
 const [responses,setResponses]=useState<Resp[]>([]); const [gates,setGates]=useState<Gate[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [rRes,gRes]=await Promise.all([fetch("/api/llm-stub-response?limit=100",{cache:"no-store"}),fetch("/api/real-llm-call-gate?limit=100",{cache:"no-store"})]); const r=await rRes.json(); const g=await gRes.json(); if(rRes.ok){ const list=Array.isArray(r.responses)?r.responses:[]; setResponses(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!gRes.ok) throw new Error(g?.error||"Real LLM Call Gates konnten nicht geladen werden."); setGates(Array.isArray(g.gates)?g.gates:[]); setSummary(g.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createGate(){ const res=await fetch("/api/real-llm-call-gate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({responseId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Gate fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="real-llm-call-gate" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fff7ed 0%,#f8fafc 100%)",borderColor:"#fdba74"}}><h1 className="section-title">Controlled Real LLM Call Gate</h1><p style={{lineHeight:1.6}}>Phase 19.0 bereitet ein Policy-Gate für spätere echte LLM-Aufrufe vor. Es wird kein produktiver LLM-Aufruf ausgeführt.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Gate vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{responses.map((resp)=><option key={resp.id} value={resp.id}>{resp.actionType || "llm-stub"} · {resp.decision} · {resp.id}</option>)}</select><button className="primary-button" type="button" onClick={createGate} disabled={!selected}>Real LLM Call Gate vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Prepared Gates</h2>{gates.length===0 ? <p>Noch keine Real LLM Call Gates.</p> : gates.map((gate)=><article key={gate.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{gate.actionType || "real-llm-gate"}</strong> <span className="chip">{gate.decision}</span></div><div className="helper-text"><code>{gate.id}</code> · {gate.timestamp}</div><p><strong>Reason:</strong> {gate.reason}</p><p><strong>Real LLM allowed:</strong> {String(gate.realLlmCallAllowed)} · <strong>Policy Gate:</strong> {String(gate.policyGateRequired)} · <strong>LLM Call:</strong> {String(gate.llmCallPerformed)} · <strong>Execution:</strong> {String(gate.executionAllowed)} · <strong>Tool:</strong> {String(gate.toolExecutionAllowed)} · <strong>Agent:</strong> {String(gate.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(gate.dryRunOnly)}</p><h3>Gate Checks</h3><ul>{gate.gateChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul><h3>Sanitized Prompt Preview</h3><pre style={{whiteSpace:"pre-wrap"}}>{gate.sanitizedPromptPreview}</pre></article>)}</section></div></main>;
}
