"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Binding={id:string;decision:string;timestamp:string;bindingMode:string};
type Preflight={id:string;timestamp:string;decision:string;reason:string;preflightMode:string;providerDispatchFinalPreflightPrepared:boolean;finalDispatchAllowed:boolean;networkCallAllowed:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchFinalPreflightPage(){
 const [bindings,setBindings]=useState<Binding[]>([]); const [preflights,setPreflights]=useState<Preflight[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [bRes,pRes]=await Promise.all([fetch("/api/provider-dispatch-token-binding?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-final-preflight?limit=100",{cache:"no-store"})]); const b=await bRes.json(); const p=await pRes.json(); if(bRes.ok){ const list=Array.isArray(b.providerDispatchTokenBindings)?b.providerDispatchTokenBindings:[]; setBindings(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!pRes.ok) throw new Error(p?.error||"Final Preflights konnten nicht geladen werden."); setPreflights(Array.isArray(p.providerDispatchFinalPreflights)?p.providerDispatchFinalPreflights:[]); setSummary(p.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createPreflight(){ const res=await fetch("/api/provider-dispatch-final-preflight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerDispatchTokenBindingId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Final Preflight fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-final-preflight" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f8fafc 0%,#eef2ff 100%)",borderColor:"#c7d2fe"}}><h1 className="section-title">Provider Dispatch Final Preflight</h1><p style={{lineHeight:1.6}}>Phase 35.0 bereitet den finalen Provider Dispatch Preflight vor. Final Dispatch bleibt nicht erlaubt. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Final Preflight vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{bindings.map((item)=><option key={item.id} value={item.id}>{item.bindingMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createPreflight} disabled={!selected}>Provider Dispatch Final Preflight vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Final Preflights</h2>{preflights.length===0?<p>Noch keine Final Preflights.</p>:preflights.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.preflightMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Prepared:</strong> {String(item.providerDispatchFinalPreflightPrepared)} · <strong>Final dispatch allowed:</strong> {String(item.finalDispatchAllowed)} · <strong>Network allowed:</strong> {String(item.networkCallAllowed)}</p><p><strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
