"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type LedgerEntry = { id: string; decision: string; timestamp: string; ledgerMode: string };
type Receipt = { id: string; timestamp: string; decision: string; reason: string; receiptMode: string; providerDispatchHumanApprovalTokenIssuanceReceiptRecorded: boolean; humanApprovalTokenIssuanceReceiptPrepared: boolean; humanApprovalTokenIssued: boolean; humanApprovalTokenActivated: boolean; humanApprovalTokenConsumed: boolean; approvalCandidateApproved: boolean; approvalCandidateExecuted: boolean; networkCallPerformed: boolean; providerExecutionAllowed: boolean; llmCallPerformed: boolean; dryRunOnly: boolean };
export default function ProviderDispatchHumanApprovalTokenIssuanceReceiptPage() {
  const [ledgers, setLedgers] = useState<LedgerEntry[]>([]); const [receipts, setReceipts] = useState<Receipt[]>([]); const [summary, setSummary] = useState<unknown>(null); const [selected, setSelected] = useState(""); const [error, setError] = useState<string | null>(null);
  async function load() { setError(null); try { const [lRes, rRes] = await Promise.all([fetch("/api/provider-dispatch-human-approval-token-issuance-ledger?limit=100", { cache: "no-store" }), fetch("/api/provider-dispatch-human-approval-token-issuance-receipt?limit=100", { cache: "no-store" })]); const l = await lRes.json(); const r = await rRes.json(); if (lRes.ok) { const list = Array.isArray(l.providerDispatchHumanApprovalTokenIssuanceLedgerEntries) ? l.providerDispatchHumanApprovalTokenIssuanceLedgerEntries : []; setLedgers(list); if (!selected && list[0]?.id) setSelected(list[0].id); } if (!rRes.ok) throw new Error(r?.error || "Receipts konnten nicht geladen werden."); setReceipts(Array.isArray(r.providerDispatchHumanApprovalTokenIssuanceReceipts) ? r.providerDispatchHumanApprovalTokenIssuanceReceipts : []); setSummary(r.summary || null); } catch (err) { setError(err instanceof Error ? err.message : "Unbekannter Fehler"); } }
  useEffect(() => { load(); }, []);
  async function createReceipt() { const res = await fetch("/api/provider-dispatch-human-approval-token-issuance-receipt", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerDispatchHumanApprovalTokenIssuanceLedgerEntryId: selected }) }); if (!res.ok) { const p = await res.json(); setError(p?.error || "Receipt fehlgeschlagen"); } await load(); }
  return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-human-approval-token-issuance-receipt" /><div className="page-shell"><section className="hero-card"><h1 className="section-title">Provider Dispatch Human Approval Token Issuance Receipt</h1><p style={{ lineHeight: 1.6 }}>Phase 47.0 schreibt einen metadata-only Receipt zur Issuance Ledger Chain. Der Receipt ist receipt-only und review-only. Der Token bleibt nicht issued, nicht aktiviert und nicht konsumiert. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{ borderColor: "#fecaca", background: "#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Receipt schreiben</h2><select className="text-input" value={selected} onChange={(ev) => setSelected(ev.target.value)}>{ledgers.map((item) => <option key={item.id} value={item.id}>{item.ledgerMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createReceipt} disabled={!selected}>Human Approval Token Issuance Receipt schreiben</button></section><section className="panel-card"><h2>Summary</h2><pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Receipts</h2>{receipts.length === 0 ? <p>Noch keine Receipts.</p> : receipts.map((item) => <article key={item.id} style={{ borderTop: "1px solid #e5e7eb", padding: "12px 0" }}><div><strong>{item.receiptMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Receipt recorded:</strong> {String(item.providerDispatchHumanApprovalTokenIssuanceReceiptRecorded)} · <strong>Prepared:</strong> {String(item.humanApprovalTokenIssuanceReceiptPrepared)} · <strong>Issued:</strong> {String(item.humanApprovalTokenIssued)} · <strong>Activated:</strong> {String(item.humanApprovalTokenActivated)} · <strong>Consumed:</strong> {String(item.humanApprovalTokenConsumed)}</p><p><strong>Approved:</strong> {String(item.approvalCandidateApproved)} · <strong>Executed:</strong> {String(item.approvalCandidateExecuted)} · <strong>Network:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
