"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Gate={id:string;decision:string;timestamp:string;gateMode:string};
type Envelope={id:string;timestamp:string;decision:string;reason:string;envelopeMode:string;providerDispatchDryRunCommandEnvelopePrepared:boolean;commandEnvelopePrepared:boolean;commandEnvelopeExecuted:boolean;executionGateOpen:boolean;finalDispatchAllowed:boolean;networkCallAllowed:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchDryRunCommandEnvelopePage(){
 const [gates,setGates]=useState<Gate[]>([]); const [envelopes,setEnvelopes]=useState<Envelope[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [gRes,eRes]=await Promise.all([fetch("/api/provider-dispatch-execution-gate?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-dry-run-command-envelope?limit=100",{cache:"no-store"})]); const g=await gRes.json(); const e=await eRes.json(); if(gRes.ok){ const list=Array.isArray(g.providerDispatchExecutionGates)?g.providerDispatchExecutionGates:[]; setGates(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!eRes.ok) throw new Error(e?.error||"Dry-Run Command Envelopes konnten nicht geladen werden."); setEnvelopes(Array.isArray(e.providerDispatchDryRunCommandEnvelopes)?e.providerDispatchDryRunCommandEnvelopes:[]); setSummary(e.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createEnvelope(){ const res=await fetch("/api/provider-dispatch-dry-run-command-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerDispatchExecutionGateId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Dry-Run Command Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-dry-run-command-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f8fafc 0%,#eef2ff 100%)",borderColor:"#c7d2fe"}}><h1 className="section-title">Provider Dispatch Dry-Run Command Envelope</h1><p style={{lineHeight:1.6}}>Phase 37.0 bereitet ein Provider Dispatch Dry-Run Command Envelope vor. Das Command Envelope wird nicht ausgeführt. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Dry-Run Command Envelope vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{gates.map((item)=><option key={item.id} value={item.id}>{item.gateMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>Provider Dispatch Dry-Run Command Envelope vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Dry-Run Command Envelopes</h2>{envelopes.length===0?<p>Noch keine Dry-Run Command Envelopes.</p>:envelopes.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.envelopeMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Prepared:</strong> {String(item.providerDispatchDryRunCommandEnvelopePrepared)} · <strong>Command prepared:</strong> {String(item.commandEnvelopePrepared)} · <strong>Command executed:</strong> {String(item.commandEnvelopeExecuted)} · <strong>Gate open:</strong> {String(item.executionGateOpen)}</p><p><strong>Final dispatch allowed:</strong> {String(item.finalDispatchAllowed)} · <strong>Network allowed:</strong> {String(item.networkCallAllowed)} · <strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
