"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Req={id:string;decision:string;timestamp:string;requestMode:string};
type Gate={id:string;timestamp:string;decision:string;reason:string;issuanceGateMode:string;issuanceState:any;providerCallPlan:any;operationalControls:any;issuanceChecks:Array<{name:string;passed:boolean;reason:string}>;networkCallPerformed:boolean;providerExecutionAllowed:boolean;realLlmCallAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function ApprovalTokenIssuanceGatePage(){
 const [requests,setRequests]=useState<Req[]>([]); const [gates,setGates]=useState<Gate[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [issuanceReason,setIssuanceReason]=useState("Token issuance gate prepared. Token not issued automatically."); const [issuanceIntent,setIssuanceIntent]=useState(false); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [rRes,gRes]=await Promise.all([fetch("/api/human-approval-token-request?limit=100",{cache:"no-store"}),fetch("/api/approval-token-issuance-gate?limit=100",{cache:"no-store"})]); const r=await rRes.json(); const g=await gRes.json(); if(rRes.ok){ const list=Array.isArray(r.approvalTokenRequests)?r.approvalTokenRequests:[]; setRequests(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!gRes.ok) throw new Error(g?.error||"Issuance Gates konnten nicht geladen werden."); setGates(Array.isArray(g.approvalTokenIssuanceGates)?g.approvalTokenIssuanceGates:[]); setSummary(g.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createGate(){ const res=await fetch("/api/approval-token-issuance-gate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approvalTokenRequestId:selected,issuanceReason,issuanceIntent})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Issuance Gate fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="approval-token-issuance-gate" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#ecfdf5 0%,#f8fafc 100%)",borderColor:"#86efac"}}><h1 className="section-title">Approval Token Issuance Gate</h1><p style={{lineHeight:1.6}}>Phase 28.0 bereitet ein separates Approval Token Issuance Gate vor. Token-Ausstellung bleibt kontrolliert und auditierbar. Kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Issuance Gate vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{requests.map((req)=><option key={req.id} value={req.id}>{req.requestMode} · {req.decision} · {req.id}</option>)}</select><label>Issuance Reason</label><textarea className="text-input" value={issuanceReason} onChange={(ev)=>setIssuanceReason(ev.target.value)} rows={3} /><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={issuanceIntent} onChange={(ev)=>setIssuanceIntent(ev.target.checked)} /> Explicit issuance intent recorded</label><button className="primary-button" type="button" onClick={createGate} disabled={!selected}>Approval Token Issuance Gate vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Issuance Gates</h2>{gates.length===0 ? <p>Noch keine Issuance Gates.</p> : gates.map((gate)=><article key={gate.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{gate.issuanceGateMode}</strong> <span className="chip">{gate.decision}</span></div><div className="helper-text"><code>{gate.id}</code> · {gate.timestamp}</div><p><strong>Reason:</strong> {gate.reason}</p><p><strong>No secrets:</strong> {String(gate.noSecretsIncluded)} · <strong>Network call:</strong> {String(gate.networkCallPerformed)} · <strong>Provider execution:</strong> {String(gate.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(gate.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(gate.llmCallPerformed)} · <strong>Dry-run:</strong> {String(gate.dryRunOnly)}</p><h3>Issuance State</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(gate.issuanceState ?? {}, null, 2)}</pre><h3>Provider Call Plan</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(gate.providerCallPlan ?? {}, null, 2)}</pre><ul>{gate.issuanceChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
