"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type Proposal = { id:string; status:string; agentName:string; purpose:string; requestedCapability?:string; proposedTools?:string[]; proposedPermissions?:string[]; riskLevel?:string; createdAt:string };
export default function AgentBlueprintsPage(){
  const [proposals,setProposals]=useState<Proposal[]>([]); const [error,setError]=useState<string|null>(null);
  const [agentName,setAgentName]=useState("CustomCapabilityAgent"); const [purpose,setPurpose]=useState("Kontrollierter Spezialagent als Blueprint-Vorschlag."); const [capability,setCapability]=useState("custom-tool-capability");
  async function load(){ setError(null); try{ const res=await fetch("/api/agent-blueprints", { cache:"no-store" }); const payload=await res.json(); if(!res.ok) throw new Error(payload?.error || "Fehler"); setProposals(Array.isArray(payload.proposals) ? payload.proposals : []); } catch(e){ setError(e instanceof Error ? e.message : "Unbekannter Fehler"); } }
  useEffect(()=>{ load(); }, []);
  async function create(){ const res=await fetch("/api/agent-blueprints", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ agentName, purpose, requestedCapability: capability, proposedTools:["capability-analyzer", "report-generator"], proposedPermissions:["read_context", "create_blueprint_report"], riskLevel:"medium" }) }); if(!res.ok){ const p=await res.json(); setError(p?.error || "Create fehlgeschlagen"); } await load(); }
  async function decide(id:string,status:"approved"|"denied"|"activated"){ const res=await fetch("/api/agent-blueprints", { method:"PATCH", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ id, status, decisionNote:"UI decision: " + status }) }); if(!res.ok){ const p=await res.json(); setError(p?.error || "Decision fehlgeschlagen"); } await load(); }
  return <main className="page-wrap">
      <UnifiedNavigation active="agent-blueprints" />
      <div className="page-shell"><section className="hero-card" style={{ background:"linear-gradient(135deg,#ede9fe 0%,#f8fafc 100%)", borderColor:"#c4b5fd" }}><h1 className="section-title">Agent Blueprint Proposals</h1><p style={{ lineHeight:1.6 }}>Hier werden kontrollierte Agent-Blueprints geprüft. Approval ist nur Freigabe für Planung/Review. Aktivierung bleibt ein separater Governance-Schritt.</p></section>{error ? <section className="panel-card" style={{ borderColor:"#fecaca", background:"#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Blueprint Proposal erstellen</h2><input className="text-input" value={agentName} onChange={(e)=>setAgentName(e.target.value)} /><input className="text-input" value={capability} onChange={(e)=>setCapability(e.target.value)} /><textarea className="text-area" value={purpose} onChange={(e)=>setPurpose(e.target.value)} /><button className="primary-button" type="button" onClick={create}>Agent Blueprint erstellen</button></section><section className="panel-card"><h2>Proposals</h2>{proposals.length===0 ? <p>Noch keine Agent Blueprint Proposals.</p> : proposals.map((p)=><article key={p.id} style={{ borderTop:"1px solid #e5e7eb", padding:"12px 0" }}><div><strong>{p.agentName}</strong> <span className="chip">{p.status}</span> {p.riskLevel ? <span className="chip">{p.riskLevel}</span> : null}</div><div className="helper-text"><code>{p.id}</code> · {p.createdAt}</div><p>{p.purpose}</p>{p.requestedCapability ? <p><strong>Capability:</strong> {p.requestedCapability}</p> : null}{p.proposedTools?.length ? <p><strong>Tools:</strong> {p.proposedTools.join(", ")}</p> : null}{p.proposedPermissions?.length ? <p><strong>Permissions:</strong> {p.proposedPermissions.join(", ")}</p> : null}{p.status === "pending_review" || p.status === "draft" ? <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}><button className="secondary-button" onClick={()=>decide(p.id,"approved")}>Approve</button><button className="secondary-button" onClick={()=>decide(p.id,"denied")}>Deny</button><button className="secondary-button" onClick={()=>decide(p.id,"activated")}>Activated</button></div> : null}</article>)}</section></div></main>;
}
