"use client";
import { useEffect, useState } from "react";
type Req = { id:string; status:string; requestedCapability:string; reason?:string; userInputPreview?:string; riskLevel?:string; requestedAt:string; decisionNote?:string };
export default function CapabilityRequestsPage(){
  const [requests,setRequests]=useState<Req[]>([]); const [error,setError]=useState<string|null>(null); const [cap,setCap]=useState("custom-tool-capability"); const [reason,setReason]=useState("Fehlende Fähigkeit für Agent Flow prüfen.");
  async function load(){ setError(null); try{ const res=await fetch("/api/capability-requests", { cache:"no-store" }); const payload=await res.json(); if(!res.ok) throw new Error(payload?.error||"Fehler"); setRequests(Array.isArray(payload.requests)?payload.requests:[]); } catch(e){ setError(e instanceof Error ? e.message : "Unbekannter Fehler"); } }
  useEffect(()=>{ load(); },[]);
  async function create(){ const res=await fetch("/api/capability-requests", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ requestedCapability: cap, reason, riskLevel:"medium" }) }); if(!res.ok){ const p=await res.json(); setError(p?.error||"Create fehlgeschlagen"); } await load(); }
  async function decide(id:string,status:"approved"|"denied"|"implemented"){ const res=await fetch("/api/capability-requests", { method:"PATCH", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ id, status, decisionNote: "UI decision: "+status }) }); if(!res.ok){ const p=await res.json(); setError(p?.error||"Decision fehlgeschlagen"); } await load(); }
  return <main className="page-wrap"><nav style={{ display:"flex", gap:12, flexWrap:"wrap", marginBottom:18 }}><a className="nav-link" href="/">Chat</a><a className="nav-link" href="/tool-consent">Tool Consent</a><a className="nav-link" href="/capability-requests">Capability Requests</a><a className="nav-link" href="/analytics">Analytics</a><a className="nav-link" href="/system">System</a></nav><div className="page-shell"><section className="hero-card" style={{ background:"linear-gradient(135deg,#e0f2fe 0%,#f8fafc 100%)", borderColor:"#7dd3fc" }}><h1 className="section-title">Missing Tool / Capability Requests</h1><p style={{ lineHeight:1.6 }}>Hier landen kontrollierte Requests, wenn der Agent eine fehlende Fähigkeit erkennt. Approval bedeutet nur Freigabe zur Analyse/Planung, nicht automatische Tool- oder Agent-Erzeugung.</p></section>{error ? <section className="panel-card" style={{ borderColor:"#fecaca", background:"#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Test Request erstellen</h2><input className="text-input" value={cap} onChange={(e)=>setCap(e.target.value)} /><textarea className="text-area" value={reason} onChange={(e)=>setReason(e.target.value)} /><button className="primary-button" type="button" onClick={create}>Capability Request erstellen</button></section><section className="panel-card"><h2>Requests</h2>{requests.length===0 ? <p>Noch keine Capability Requests.</p> : requests.map((r)=><article key={r.id} style={{ borderTop:"1px solid #e5e7eb", padding:"12px 0" }}><div><strong>{r.requestedCapability}</strong> <span className="chip">{r.status}</span> {r.riskLevel ? <span className="chip">{r.riskLevel}</span> : null}</div><div className="helper-text"><code>{r.id}</code> · {r.requestedAt}</div>{r.reason ? <p>{r.reason}</p> : null}{r.userInputPreview ? <pre style={{ whiteSpace:"pre-wrap" }}>{r.userInputPreview}</pre> : null}{r.status === "pending" ? <div style={{ display:"flex", gap:8, flexWrap:"wrap" }}><button className="secondary-button" onClick={()=>decide(r.id,"approved")}>Approve</button><button className="secondary-button" onClick={()=>decide(r.id,"denied")}>Deny</button><button className="secondary-button" onClick={()=>decide(r.id,"implemented")}>Implemented</button></div> : null}</article>)}</section></div></main>;
}
