"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type Confirmation = { id: string; decision: string; timestamp: string; envelopeMode: string };
type LedgerEntry = { id: string; timestamp: string; decision: string; reason: string; ledgerMode: string; humanApprovalTokenIssuanceConfirmedForReviewOnly: boolean; humanApprovalTokenReadyForIssuanceReview: boolean; humanApprovalTokenIssued: boolean; humanApprovalTokenActivated: boolean; humanApprovalTokenConsumed: boolean; approvalCandidateApproved: boolean; approvalCandidateExecuted: boolean; networkCallPerformed: boolean; providerExecutionAllowed: boolean; llmCallPerformed: boolean; dryRunOnly: boolean };
export default function ProviderDispatchHumanApprovalTokenIssuanceLedgerPage() {
  const [confirmations, setConfirmations] = useState<Confirmation[]>([]); const [entries, setEntries] = useState<LedgerEntry[]>([]); const [summary, setSummary] = useState<unknown>(null); const [selected, setSelected] = useState(""); const [error, setError] = useState<string | null>(null);
  async function load() { setError(null); try { const [cRes, lRes] = await Promise.all([fetch("/api/provider-dispatch-human-approval-token-issuance-confirmation?limit=100", { cache: "no-store" }), fetch("/api/provider-dispatch-human-approval-token-issuance-ledger?limit=100", { cache: "no-store" })]); const c = await cRes.json(); const l = await lRes.json(); if (cRes.ok) { const list = Array.isArray(c.providerDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes) ? c.providerDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes : []; setConfirmations(list); if (!selected && list[0]?.id) setSelected(list[0].id); } if (!lRes.ok) throw new Error(l?.error || "Ledger konnte nicht geladen werden."); setEntries(Array.isArray(l.providerDispatchHumanApprovalTokenIssuanceLedgerEntries) ? l.providerDispatchHumanApprovalTokenIssuanceLedgerEntries : []); setSummary(l.summary || null); } catch (err) { setError(err instanceof Error ? err.message : "Unbekannter Fehler"); } }
  useEffect(() => { load(); }, []);
  async function createEntry() { const res = await fetch("/api/provider-dispatch-human-approval-token-issuance-ledger", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerDispatchHumanApprovalTokenIssuanceConfirmationEnvelopeId: selected }) }); if (!res.ok) { const p = await res.json(); setError(p?.error || "Ledger Entry fehlgeschlagen"); } await load(); }
  return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-human-approval-token-issuance-ledger" /><div className="page-shell"><section className="hero-card"><h1 className="section-title">Provider Dispatch Human Approval Token Issuance Ledger</h1><p style={{ lineHeight: 1.6 }}>Phase 46.0 schreibt einen metadata-only Ledger Entry zur Issuance Confirmation. Der Ledger ist ledger-only und review-only. Der Token bleibt nicht issued, nicht aktiviert und nicht konsumiert. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{ borderColor: "#fecaca", background: "#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Ledger Entry schreiben</h2><select className="text-input" value={selected} onChange={(ev) => setSelected(ev.target.value)}>{confirmations.map((item) => <option key={item.id} value={item.id}>{item.envelopeMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createEntry} disabled={!selected}>Human Approval Token Issuance Ledger schreiben</button></section><section className="panel-card"><h2>Summary</h2><pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Ledger Entries</h2>{entries.length === 0 ? <p>Noch keine Ledger Entries.</p> : entries.map((item) => <article key={item.id} style={{ borderTop: "1px solid #e5e7eb", padding: "12px 0" }}><div><strong>{item.ledgerMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Review-only confirmed:</strong> {String(item.humanApprovalTokenIssuanceConfirmedForReviewOnly)} · <strong>Issuance review:</strong> {String(item.humanApprovalTokenReadyForIssuanceReview)} · <strong>Issued:</strong> {String(item.humanApprovalTokenIssued)} · <strong>Activated:</strong> {String(item.humanApprovalTokenActivated)} · <strong>Consumed:</strong> {String(item.humanApprovalTokenConsumed)}</p><p><strong>Approved:</strong> {String(item.approvalCandidateApproved)} · <strong>Executed:</strong> {String(item.approvalCandidateExecuted)} · <strong>Network:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
