"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type Entry = { id:string; status:string; agentName:string; purpose:string; requestedCapability?:string; allowedTools?:string[]; permissions?:string[]; riskLevel?:string; updatedAt:string; activationNote?:string };
export default function AgentRegistryPage(){
  const [entries,setEntries]=useState<Entry[]>([]); const [error,setError]=useState<string|null>(null);
  const [agentName,setAgentName]=useState("CustomCapabilityAgent"); const [purpose,setPurpose]=useState("Kontrolliert registrierter Test-Agent ohne automatische Ausführung."); const [capability,setCapability]=useState("custom-tool-capability");
  async function load(){ setError(null); try{ const res=await fetch("/api/agent-registry", { cache:"no-store" }); const payload=await res.json(); if(!res.ok) throw new Error(payload?.error || "Fehler"); setEntries(Array.isArray(payload.entries) ? payload.entries : []); } catch(e){ setError(e instanceof Error ? e.message : "Unbekannter Fehler"); } }
  useEffect(()=>{ load(); }, []);
  async function create(){ const res=await fetch("/api/agent-registry", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ agentName, purpose, requestedCapability: capability, allowedTools:["capability-analyzer"], permissions:["read_context"], riskLevel:"medium" }) }); if(!res.ok){ const p=await res.json(); setError(p?.error || "Registrierung fehlgeschlagen"); } await load(); }
  async function setStatus(id:string,status:"registered"|"disabled"|"test_mode"|"active"){ const res=await fetch("/api/agent-registry", { method:"PATCH", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ id, status, activationNote:"UI status change: " + status }) }); if(!res.ok){ const p=await res.json(); setError(p?.error || "Status fehlgeschlagen"); } await load(); }
  return <main className="page-wrap">
      <UnifiedNavigation active="agent-registry" />
      <div className="page-shell"><section className="hero-card" style={{ background:"linear-gradient(135deg,#fef3c7 0%,#f8fafc 100%)", borderColor:"#fde68a" }}><h1 className="section-title">Controlled Agent Registry</h1><p style={{ lineHeight:1.6 }}>Hier werden Agenten kontrolliert registriert. Registrierung bedeutet nicht automatische Ausführung; aktive Nutzung bleibt consent- und permission-gesteuert.</p></section>{error ? <section className="panel-card" style={{ borderColor:"#fecaca", background:"#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Agent registrieren</h2><input className="text-input" value={agentName} onChange={(e)=>setAgentName(e.target.value)} /><input className="text-input" value={capability} onChange={(e)=>setCapability(e.target.value)} /><textarea className="text-area" value={purpose} onChange={(e)=>setPurpose(e.target.value)} /><button className="primary-button" type="button" onClick={create}>Agent in Test Mode registrieren</button></section><section className="panel-card"><h2>Registry</h2>{entries.length===0 ? <p>Noch keine Controlled Agents.</p> : entries.map((entry)=><article key={entry.id} style={{ borderTop:"1px solid #e5e7eb", padding:"12px 0" }}><div><strong>{entry.agentName}</strong> <span className="chip">{entry.status}</span> {entry.riskLevel ? <span className="chip">{entry.riskLevel}</span> : null}</div><div className="helper-text"><code>{entry.id}</code> · {entry.updatedAt}</div><p>{entry.purpose}</p>{entry.requestedCapability ? <p><strong>Capability:</strong> {entry.requestedCapability}</p> : null}{entry.allowedTools?.length ? <p><strong>Allowed Tools:</strong> {entry.allowedTools.join(", ")}</p> : null}{entry.permissions?.length ? <p><strong>Permissions:</strong> {entry.permissions.join(", ")}</p> : null}<div style={{ display:"flex", gap:8, flexWrap:"wrap" }}><button className="secondary-button" onClick={()=>setStatus(entry.id,"test_mode")}>Test Mode</button><button className="secondary-button" onClick={()=>setStatus(entry.id,"registered")}>Registered</button><button className="secondary-button" onClick={()=>setStatus(entry.id,"active")}>Active</button><button className="secondary-button" onClick={()=>setStatus(entry.id,"disabled")}>Disabled</button></div></article>)}</section></div></main>;
}
