"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Envelope={id:string;decision:string;timestamp:string;envelopeMode:string};
type Readiness={id:string;timestamp:string;decision:string;reason:string;readinessMode:string;readinessChecks:Array<{name:string;passed:boolean;reason:string}>;providerDispatchPrepared:boolean;providerDispatchPerformed:boolean;metadataOnly:boolean;provider:string;modelSelected:string;dispatchPayloadIncluded:boolean;envelopePayloadIncluded:boolean;promptPayloadIncluded:boolean;secretValuesIncluded:boolean;requestBodyIncluded:boolean;sensitiveRequestBodyIncluded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchReadinessPage(){
 const [envelopes,setEnvelopes]=useState<Envelope[]>([]); const [items,setItems]=useState<Readiness[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [eRes,rRes]=await Promise.all([fetch("/api/provider-request-envelope?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-readiness?limit=100",{cache:"no-store"})]); const e=await eRes.json(); const r=await rRes.json(); if(eRes.ok){ const list=Array.isArray(e.providerRequestEnvelopes)?e.providerRequestEnvelopes:[]; setEnvelopes(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!rRes.ok) throw new Error(r?.error||"Provider Dispatch Readiness konnten nicht geladen werden."); setItems(Array.isArray(r.providerDispatchReadiness)?r.providerDispatchReadiness:[]); setSummary(r.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function create(){ const res=await fetch("/api/provider-dispatch-readiness",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerRequestEnvelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Provider Dispatch Readiness fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-readiness" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fefce8 0%,#f8fafc 100%)",borderColor:"#fde68a"}}><h1 className="section-title">Provider Dispatch Readiness</h1><p style={{lineHeight:1.6}}>Phase 33.0 bereitet Provider Dispatch Readiness metadata-only vor. Kein Provider Dispatch, kein Provider-/Netzwerk-Aufruf, kein Prompt Payload, keine Secret-Werte, kein sensibler Request Body.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Provider Dispatch Readiness vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{envelopes.map((item)=><option key={item.id} value={item.id}>{item.envelopeMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={create} disabled={!selected}>Provider Dispatch Readiness vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Readiness</h2>{items.length===0?<p>Noch keine Provider Dispatch Readiness.</p>:items.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.readinessMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Prepared:</strong> {String(item.providerDispatchPrepared)} · <strong>Dispatch performed:</strong> {String(item.providerDispatchPerformed)} · <strong>Metadata-only:</strong> {String(item.metadataOnly)} · <strong>Provider:</strong> {item.provider} · <strong>Model:</strong> {item.modelSelected}</p><p><strong>Dispatch payload:</strong> {String(item.dispatchPayloadIncluded)} · <strong>Envelope payload:</strong> {String(item.envelopePayloadIncluded)} · <strong>Prompt payload:</strong> {String(item.promptPayloadIncluded)} · <strong>Secrets:</strong> {String(item.secretValuesIncluded)} · <strong>Request body:</strong> {String(item.requestBodyIncluded)} · <strong>Sensitive body:</strong> {String(item.sensitiveRequestBodyIncluded)}</p><p><strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p><ul>{item.readinessChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
