"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Preflight={id:string;decision:string;timestamp:string;readinessMode:string};
type Env={id:string;timestamp:string;decision:string;reason:string;simulationMode:string;simulationChecks:Array<{name:string;passed:boolean;reason:string}>;simulatedProviderRequest:any;simulatedProviderResponse:any;operationalMetadata:any;networkCallPerformed:boolean;providerExecutionAllowed:boolean;realLlmCallAllowed:boolean;llmCallPerformed:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function ControlledProviderInvocationSimulationEnvelopePage(){
 const [preflights,setPreflights]=useState<Preflight[]>([]); const [envelopes,setEnvelopes]=useState<Env[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [pRes,eRes]=await Promise.all([fetch("/api/provider-invocation-readiness-preflight?limit=100",{cache:"no-store"}),fetch("/api/controlled-provider-invocation-simulation-envelope?limit=100",{cache:"no-store"})]); const p=await pRes.json(); const e=await eRes.json(); if(pRes.ok){ const list=Array.isArray(p.preflights)?p.preflights:[]; setPreflights(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!eRes.ok) throw new Error(e?.error||"Simulation Envelopes konnten nicht geladen werden."); setEnvelopes(Array.isArray(e.simulationEnvelopes)?e.simulationEnvelopes:[]); setSummary(e.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createEnvelope(){ const res=await fetch("/api/controlled-provider-invocation-simulation-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preflightId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Simulation Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="controlled-provider-invocation-simulation-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#ecfeff 0%,#f8fafc 100%)",borderColor:"#67e8f9"}}><h1 className="section-title">Controlled Provider Invocation Simulation Envelope</h1><p style={{lineHeight:1.6}}>Phase 25.0 bereitet eine kontrollierte Provider Invocation Simulation Envelope vor. Keine echten Provider-/Netzwerk-Aufrufe, keine Tool-/Agent-Ausführung, Response nur simuliert/metadata-only.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Simulation Envelope erstellen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{preflights.map((p)=><option key={p.id} value={p.id}>{p.readinessMode} · {p.decision} · {p.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>Controlled Provider Simulation Envelope vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Simulation Envelopes</h2>{envelopes.length===0 ? <p>Noch keine Simulation Envelopes.</p> : envelopes.map((env)=><article key={env.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{env.simulationMode}</strong> <span className="chip">{env.decision}</span></div><div className="helper-text"><code>{env.id}</code> · {env.timestamp}</div><p><strong>Reason:</strong> {env.reason}</p><p><strong>No secrets:</strong> {String(env.noSecretsIncluded)} · <strong>Network call:</strong> {String(env.networkCallPerformed)} · <strong>Provider execution:</strong> {String(env.providerExecutionAllowed)} · <strong>Real LLM allowed:</strong> {String(env.realLlmCallAllowed)} · <strong>LLM Call:</strong> {String(env.llmCallPerformed)} · <strong>Execution:</strong> {String(env.executionAllowed)} · <strong>Tool:</strong> {String(env.toolExecutionAllowed)} · <strong>Agent:</strong> {String(env.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(env.dryRunOnly)}</p><h3>Simulated Provider Request</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(env.simulatedProviderRequest ?? {}, null, 2)}</pre><h3>Simulated Provider Response</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(env.simulatedProviderResponse ?? {}, null, 2)}</pre><h3>Operational Metadata</h3><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(env.operationalMetadata ?? {}, null, 2)}</pre><ul>{env.simulationChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
