import { createProviderDispatchHumanApprovalTokenIssuanceConfirmationEnvelope, listProviderDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes, summarizeProviderDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes } from "../../../lib/provider-dispatch-human-approval-token-issuance-confirmation-store";
export const dynamic = "force-dynamic";
export async function GET(request: Request) {
  try { const url = new URL(request.url); const limit = Number(url.searchParams.get("limit") || "100"); const providerDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes = listProviderDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes(Number.isFinite(limit) ? limit : 100); return Response.json({ ok: true, summary: summarizeProviderDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes(providerDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes), providerDispatchHumanApprovalTokenIssuanceConfirmationEnvelopes }); }
  catch (error) { const message = error instanceof Error ? error.message : "Provider Dispatch Human Approval Token Issuance Confirmation Envelopes konnten nicht gelesen werden."; return Response.json({ ok: false, error: message }, { status: 500 }); }
}
export async function POST(request: Request) {
  try { const body = await request.json(); const envelope = createProviderDispatchHumanApprovalTokenIssuanceConfirmationEnvelope({ providerDispatchHumanApprovalTokenIssuanceCandidatePolicySimulationId: typeof body.providerDispatchHumanApprovalTokenIssuanceCandidatePolicySimulationId === "string" ? body.providerDispatchHumanApprovalTokenIssuanceCandidatePolicySimulationId : undefined, metadata: body.metadata && typeof body.metadata === "object" ? body.metadata : undefined }); return Response.json({ ok: true, envelope }); }
  catch (error) { const message = error instanceof Error ? error.message : "Provider Dispatch Human Approval Token Issuance Confirmation Envelope konnte nicht erstellt werden."; return Response.json({ ok: false, error: message }, { status: 400 }); }
}
