"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type ResultEnvelope={id:string;decision:string;timestamp:string;envelopeMode:string};
type TranscriptEnvelope={id:string;timestamp:string;decision:string;reason:string;transcriptMode:string;providerDispatchTranscriptEnvelopePrepared:boolean;transcriptEnvelopePrepared:boolean;transcriptEnvelopePersisted:boolean;transcriptEnvelopeContainsProviderResponse:boolean;transcriptEnvelopeContainsPromptPayload:boolean;transcriptEnvelopeContainsSecrets:boolean;commandEnvelopeExecuted:boolean;executionGateOpen:boolean;finalDispatchAllowed:boolean;networkCallAllowed:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchTranscriptEnvelopePage(){
 const [resultEnvelopes,setResultEnvelopes]=useState<ResultEnvelope[]>([]); const [transcripts,setTranscripts]=useState<TranscriptEnvelope[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [rRes,tRes]=await Promise.all([fetch("/api/provider-dispatch-dry-run-result-envelope?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-transcript-envelope?limit=100",{cache:"no-store"})]); const r=await rRes.json(); const t=await tRes.json(); if(rRes.ok){ const list=Array.isArray(r.providerDispatchDryRunResultEnvelopes)?r.providerDispatchDryRunResultEnvelopes:[]; setResultEnvelopes(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!tRes.ok) throw new Error(t?.error||"Transcript Envelopes konnten nicht geladen werden."); setTranscripts(Array.isArray(t.providerDispatchTranscriptEnvelopes)?t.providerDispatchTranscriptEnvelopes:[]); setSummary(t.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createEnvelope(){ const res=await fetch("/api/provider-dispatch-transcript-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerDispatchDryRunResultEnvelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Transcript Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-transcript-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f8fafc 0%,#eef2ff 100%)",borderColor:"#c7d2fe"}}><h1 className="section-title">Provider Dispatch Transcript Envelope</h1><p style={{lineHeight:1.6}}>Phase 39.0 bereitet ein Provider Dispatch Transcript Envelope vor. Das Transcript Envelope enthält keine Provider Response, keinen Prompt Payload und keine Secrets. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Transcript Envelope vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{resultEnvelopes.map((item)=><option key={item.id} value={item.id}>{item.envelopeMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>Provider Dispatch Transcript Envelope vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Transcript Envelopes</h2>{transcripts.length===0?<p>Noch keine Transcript Envelopes.</p>:transcripts.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.transcriptMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Prepared:</strong> {String(item.providerDispatchTranscriptEnvelopePrepared)} · <strong>Persisted:</strong> {String(item.transcriptEnvelopePersisted)} · <strong>Provider response:</strong> {String(item.transcriptEnvelopeContainsProviderResponse)} · <strong>Prompt payload:</strong> {String(item.transcriptEnvelopeContainsPromptPayload)} · <strong>Secrets:</strong> {String(item.transcriptEnvelopeContainsSecrets)}</p><p><strong>Command executed:</strong> {String(item.commandEnvelopeExecuted)} · <strong>Gate open:</strong> {String(item.executionGateOpen)} · <strong>Final dispatch allowed:</strong> {String(item.finalDispatchAllowed)} · <strong>Network allowed:</strong> {String(item.networkCallAllowed)} · <strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
