"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type ActivationGate={id:string;decision:string;timestamp:string;activationGateMode:string};
type Preflight={id:string;timestamp:string;decision:string;reason:string;preflightMode:string;preflightChecks:Array<{name:string;passed:boolean;reason:string}>;tokenBackedPreflightPrepared:boolean;tokenActive:boolean;provider:string;modelSelected:string;promptIncluded:boolean;secretValuesIncluded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function TokenBackedProviderInvocationPreflightPage(){
 const [gates,setGates]=useState<ActivationGate[]>([]); const [items,setItems]=useState<Preflight[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [gRes,pRes]=await Promise.all([fetch("/api/approval-token-activation-gate?limit=100",{cache:"no-store"}),fetch("/api/token-backed-provider-invocation-preflight?limit=100",{cache:"no-store"})]); const g=await gRes.json(); const p=await pRes.json(); if(gRes.ok){ const list=Array.isArray(g.approvalTokenActivationGates)?g.approvalTokenActivationGates:[]; setGates(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!pRes.ok) throw new Error(p?.error||"Token-backed Preflights konnten nicht geladen werden."); setItems(Array.isArray(p.tokenBackedProviderInvocationPreflights)?p.tokenBackedProviderInvocationPreflights:[]); setSummary(p.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function create(){ const res=await fetch("/api/token-backed-provider-invocation-preflight",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({activationGateId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Preflight fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="token-backed-provider-invocation-preflight" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fefce8 0%,#f8fafc 100%)",borderColor:"#fde68a"}}><h1 className="section-title">Token-Backed Provider Invocation Preflight</h1><p style={{lineHeight:1.6}}>Phase 30.0 bereitet einen Token-backed Provider Invocation Preflight vor. Kein Provider-/Netzwerk-Aufruf, kein Prompt, keine Secret-Werte.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Preflight vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{gates.map((gate)=><option key={gate.id} value={gate.id}>{gate.activationGateMode} · {gate.decision} · {gate.id}</option>)}</select><button className="primary-button" type="button" onClick={create} disabled={!selected}>Token-backed Provider Preflight vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Preflights</h2>{items.length===0?<p>Noch keine Token-backed Preflights.</p>:items.map((item)=><article key={item.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{item.preflightMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Preflight:</strong> {String(item.tokenBackedPreflightPrepared)} · <strong>Token active:</strong> {String(item.tokenActive)} · <strong>Provider:</strong> {item.provider} · <strong>Model:</strong> {item.modelSelected}</p><p><strong>Prompt included:</strong> {String(item.promptIncluded)} · <strong>Secrets:</strong> {String(item.secretValuesIncluded)} · <strong>Network call:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p><ul>{item.preflightChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
