"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Readiness={id:string;decision:string;timestamp:string};
type Activation={id:string;decision:string;timestamp:string};
type Binding={id:string;timestamp:string;decision:string;reason:string;bindingMode:string;providerDispatchTokenBindingPrepared:boolean;tokenBoundToDispatch:boolean;tokenBindingActive:boolean;tokenActive:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean};
export default function ProviderDispatchTokenBindingPage(){
 const [readiness,setReadiness]=useState<Readiness[]>([]); const [activations,setActivations]=useState<Activation[]>([]); const [bindings,setBindings]=useState<Binding[]>([]); const [summary,setSummary]=useState<any>(null); const [selectedReadiness,setSelectedReadiness]=useState(""); const [selectedActivation,setSelectedActivation]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [rRes,aRes,bRes]=await Promise.all([fetch("/api/provider-dispatch-readiness?limit=100",{cache:"no-store"}),fetch("/api/approval-token-activation-gate?limit=100",{cache:"no-store"}),fetch("/api/provider-dispatch-token-binding?limit=100",{cache:"no-store"})]); const r=await rRes.json(); const a=await aRes.json(); const b=await bRes.json(); if(rRes.ok){ const list=Array.isArray(r.providerDispatchReadiness)?r.providerDispatchReadiness:[]; setReadiness(list); if(!selectedReadiness && list[0]?.id) setSelectedReadiness(list[0].id); } if(aRes.ok){ const list=Array.isArray(a.approvalTokenActivationGates)?a.approvalTokenActivationGates:[]; setActivations(list); if(!selectedActivation && list[0]?.id) setSelectedActivation(list[0].id); } if(!bRes.ok) throw new Error(b?.error||"Bindings konnten nicht geladen werden."); setBindings(Array.isArray(b.providerDispatchTokenBindings)?b.providerDispatchTokenBindings:[]); setSummary(b.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createBinding(){ const res=await fetch("/api/provider-dispatch-token-binding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerDispatchReadinessId:selectedReadiness, tokenActivationGateId:selectedActivation})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Binding fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-token-binding" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f8fafc 0%,#eef2ff 100%)",borderColor:"#c7d2fe"}}><h1 className="section-title">Provider Dispatch Token Binding</h1><p style={{lineHeight:1.6}}>Phase 34.0 bereitet eine Token-Bindung an Provider Dispatch Readiness vor. Token wird nicht aktiv gebunden. Kein Provider Dispatch, kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Token Binding vorbereiten</h2><label>Provider Dispatch Readiness</label><select className="text-input" value={selectedReadiness} onChange={(ev)=>setSelectedReadiness(ev.target.value)}>{readiness.map((item)=><option key={item.id} value={item.id}>{item.decision} · {item.id}</option>)}</select><label>Approval Token Activation Gate</label><select className="text-input" value={selectedActivation} onChange={(ev)=>setSelectedActivation(ev.target.value)}>{activations.map((item)=><option key={item.id} value={item.id}>{item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createBinding} disabled={!selectedReadiness}>Provider Dispatch Token Binding vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Bindings</h2>{bindings.length===0?<p>Noch keine Bindings.</p>:bindings.map((binding)=><article key={binding.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{binding.bindingMode}</strong> <span className="chip">{binding.decision}</span></div><div className="helper-text"><code>{binding.id}</code> · {binding.timestamp}</div><p><strong>Reason:</strong> {binding.reason}</p><p><strong>Prepared:</strong> {String(binding.providerDispatchTokenBindingPrepared)} · <strong>Token bound:</strong> {String(binding.tokenBoundToDispatch)} · <strong>Binding active:</strong> {String(binding.tokenBindingActive)} · <strong>Token active:</strong> {String(binding.tokenActive)}</p><p><strong>Network call:</strong> {String(binding.networkCallPerformed)} · <strong>Provider execution:</strong> {String(binding.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(binding.llmCallPerformed)} · <strong>Dry-run:</strong> {String(binding.dryRunOnly)}</p></article>)}</section></div></main>;
}
