"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type Simulation = { id: string; decision: string; timestamp: string; policyMode: string };
type Envelope = { id: string; timestamp: string; decision: string; reason: string; envelopeMode: string; humanApprovalTokenReadyForIssuanceReview: boolean; humanApprovalTokenIssued: boolean; humanApprovalTokenActivated: boolean; humanApprovalTokenConsumed: boolean; approvalCandidateApproved: boolean; approvalCandidateExecuted: boolean; networkCallPerformed: boolean; providerExecutionAllowed: boolean; llmCallPerformed: boolean; dryRunOnly: boolean };
export default function ProviderDispatchHumanApprovalTokenIssuanceCandidatePage() {
  const [simulations, setSimulations] = useState<Simulation[]>([]); const [envelopes, setEnvelopes] = useState<Envelope[]>([]); const [summary, setSummary] = useState<unknown>(null); const [selected, setSelected] = useState(""); const [error, setError] = useState<string | null>(null);
  async function load() { setError(null); try { const [sRes, eRes] = await Promise.all([fetch("/api/provider-dispatch-human-approval-token-policy?limit=100", { cache: "no-store" }), fetch("/api/provider-dispatch-human-approval-token-issuance-candidate?limit=100", { cache: "no-store" })]); const s = await sRes.json(); const e = await eRes.json(); if (sRes.ok) { const list = Array.isArray(s.simulations) ? s.simulations : []; setSimulations(list); if (!selected && list[0]?.id) setSelected(list[0].id); } if (!eRes.ok) throw new Error(e?.error || "Issuance Candidate Envelopes konnten nicht geladen werden."); setEnvelopes(Array.isArray(e.providerDispatchHumanApprovalTokenIssuanceCandidateEnvelopes) ? e.providerDispatchHumanApprovalTokenIssuanceCandidateEnvelopes : []); setSummary(e.summary || null); } catch (err) { setError(err instanceof Error ? err.message : "Unbekannter Fehler"); } }
  useEffect(() => { load(); }, []);
  async function createEnvelope() { const res = await fetch("/api/provider-dispatch-human-approval-token-issuance-candidate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerDispatchHumanApprovalTokenPolicySimulationId: selected }) }); if (!res.ok) { const p = await res.json(); setError(p?.error || "Issuance Candidate fehlgeschlagen"); } await load(); }
  return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-human-approval-token-issuance-candidate" /><div className="page-shell"><section className="hero-card"><h1 className="section-title">Provider Dispatch Human Approval Token Issuance Candidate</h1><p style={{ lineHeight: 1.6 }}>Phase 44.0 bereitet einen Human Approval Token Issuance Candidate metadata-only vor. Der Token bleibt nicht issued, nicht aktiviert und nicht konsumiert. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{ borderColor: "#fecaca", background: "#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Issuance Candidate vorbereiten</h2><select className="text-input" value={selected} onChange={(ev) => setSelected(ev.target.value)}>{simulations.map((item) => <option key={item.id} value={item.id}>{item.policyMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>Human Approval Token Issuance Candidate vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Issuance Candidate Envelopes</h2>{envelopes.length === 0 ? <p>Noch keine Issuance Candidate Envelopes.</p> : envelopes.map((item) => <article key={item.id} style={{ borderTop: "1px solid #e5e7eb", padding: "12px 0" }}><div><strong>{item.envelopeMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Ready for issuance review:</strong> {String(item.humanApprovalTokenReadyForIssuanceReview)} · <strong>Issued:</strong> {String(item.humanApprovalTokenIssued)} · <strong>Activated:</strong> {String(item.humanApprovalTokenActivated)} · <strong>Consumed:</strong> {String(item.humanApprovalTokenConsumed)}</p><p><strong>Approved:</strong> {String(item.approvalCandidateApproved)} · <strong>Executed:</strong> {String(item.approvalCandidateExecuted)} · <strong>Network:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
