"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Preflight={id:string;decision:string;timestamp:string;preflightMode:string};
type Sim={id:string;timestamp:string;decision:string;reason:string;policyMode:string;policyChecks:Array<{name:string;passed:boolean;reason:string}>;tokenBackedPreflightPrepared:boolean;tokenActive:boolean;provider:string;modelSelected:string;promptIncluded:boolean;secretValuesIncluded:boolean;networkCallPerformed:boolean;providerExecutionAllowed:boolean;llmCallPerformed:boolean;dryRunOnly:boolean;noSecretsIncluded:boolean};
export default function TokenBackedProviderPreflightPolicyPage(){
 const [preflights,setPreflights]=useState<Preflight[]>([]); const [sims,setSims]=useState<Sim[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [pRes,sRes]=await Promise.all([fetch("/api/token-backed-provider-invocation-preflight?limit=100",{cache:"no-store"}),fetch("/api/token-backed-provider-preflight-policy?limit=100",{cache:"no-store"})]); const p=await pRes.json(); const s=await sRes.json(); if(pRes.ok){ const list=Array.isArray(p.tokenBackedProviderInvocationPreflights)?p.tokenBackedProviderInvocationPreflights:[]; setPreflights(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!sRes.ok) throw new Error(s?.error||"Policy Simulations konnten nicht geladen werden."); setSims(Array.isArray(s.simulations)?s.simulations:[]); setSummary(s.summary||null); }catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function simulate(){ const res=await fetch("/api/token-backed-provider-preflight-policy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preflightId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Policy Simulation fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="token-backed-provider-preflight-policy" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f5f3ff 0%,#f8fafc 100%)",borderColor:"#ddd6fe"}}><h1 className="section-title">Token-Backed Provider Preflight Policy</h1><p style={{lineHeight:1.6}}>Phase 30.1 simuliert Policy Checks für Token-backed Provider Preflights. Kein Provider-/Netzwerk-Aufruf, kein Prompt, keine Secret-Werte.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Policy Simulation erstellen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{preflights.map((item)=><option key={item.id} value={item.id}>{item.preflightMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={simulate} disabled={!selected}>Token-backed Provider Preflight Policy simulieren</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary??{},null,2)}</pre></section><section className="panel-card"><h2>Policy Simulations</h2>{sims.length===0?<p>Noch keine Policy Simulations.</p>:sims.map((sim)=><article key={sim.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{sim.policyMode}</strong> <span className="chip">{sim.decision}</span></div><div className="helper-text"><code>{sim.id}</code> · {sim.timestamp}</div><p><strong>Reason:</strong> {sim.reason}</p><p><strong>Preflight:</strong> {String(sim.tokenBackedPreflightPrepared)} · <strong>Token active:</strong> {String(sim.tokenActive)} · <strong>Provider:</strong> {sim.provider} · <strong>Model:</strong> {sim.modelSelected}</p><p><strong>Prompt included:</strong> {String(sim.promptIncluded)} · <strong>Secrets:</strong> {String(sim.secretValuesIncluded)} · <strong>Network call:</strong> {String(sim.networkCallPerformed)} · <strong>Provider execution:</strong> {String(sim.providerExecutionAllowed)} · <strong>LLM Call:</strong> {String(sim.llmCallPerformed)} · <strong>Dry-run:</strong> {String(sim.dryRunOnly)}</p><ul>{sim.policyChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
