"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Env={id:string;decision:string;actionType?:string;timestamp:string};
type Resp={id:string;timestamp:string;decision:string;actionType?:string;reason:string;responseText:string;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;llmRoutingPrepOnly:boolean;llmCallPerformed:boolean;stubOnly:boolean;noSecretsIncluded:boolean};
export default function LlmStubResponsePage(){
 const [envelopes,setEnvelopes]=useState<Env[]>([]); const [responses,setResponses]=useState<Resp[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [eRes,rRes]=await Promise.all([fetch("/api/llm-routing-envelope?limit=100",{cache:"no-store"}),fetch("/api/llm-stub-response?limit=100",{cache:"no-store"})]); const e=await eRes.json(); const r=await rRes.json(); if(eRes.ok){ const list=Array.isArray(e.envelopes)?e.envelopes:[]; setEnvelopes(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!rRes.ok) throw new Error(r?.error||"LLM Stub Responses konnten nicht geladen werden."); setResponses(Array.isArray(r.responses)?r.responses:[]); setSummary(r.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createResponse(){ const res=await fetch("/api/llm-stub-response",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({envelopeId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Stub Response fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="llm-stub-response" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#f0fdf4 0%,#f8fafc 100%)",borderColor:"#86efac"}}><h1 className="section-title">Controlled LLM Stub Response</h1><p style={{lineHeight:1.6}}>Phase 18.0 erzeugt eine trockene Explainer Response aus einem Controlled LLM Routing Envelope. Kein produktiver LLM-Aufruf, keine Ausführung.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Stub Response erstellen</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{envelopes.map((env)=><option key={env.id} value={env.id}>{env.actionType || "llm-routing"} · {env.decision} · {env.id}</option>)}</select><button className="primary-button" type="button" onClick={createResponse} disabled={!selected}>Dry-run Explainer Response erzeugen</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Stub Responses</h2>{responses.length===0 ? <p>Noch keine Stub Responses.</p> : responses.map((resp)=><article key={resp.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{resp.actionType || "llm-stub"}</strong> <span className="chip">{resp.decision}</span></div><div className="helper-text"><code>{resp.id}</code> · {resp.timestamp}</div><p><strong>Reason:</strong> {resp.reason}</p><p><strong>Execution:</strong> {String(resp.executionAllowed)} · <strong>Tool:</strong> {String(resp.toolExecutionAllowed)} · <strong>Agent:</strong> {String(resp.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(resp.dryRunOnly)} · <strong>LLM Routing Prep:</strong> {String(resp.llmRoutingPrepOnly)} · <strong>LLM Call:</strong> {String(resp.llmCallPerformed)} · <strong>Stub:</strong> {String(resp.stubOnly)} · <strong>No Secrets:</strong> {String(resp.noSecretsIncluded)}</p><h3>Dry-run Explainer Response</h3><pre style={{whiteSpace:"pre-wrap"}}>{resp.responseText}</pre></article>)}</section></div></main>;
}
