"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Consent={id:string;decision:string;actionType?:string;timestamp:string;consentScope?:{approvalStatus:string;expiresAt:string}};
type Env={id:string;timestamp:string;decision:string;actionType?:string;reason:string;promptPreview:string;realLlmCallAllowed:boolean;llmCallPerformed:boolean;consentRequired:boolean;humanApprovalRequired:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;approvalState:any;envelopeChecks:Array<{name:string;passed:boolean;reason:string}>};
export default function ApprovedRealLlmInvocationEnvelopePage(){
 const [requests,setRequests]=useState<Consent[]>([]); const [envelopes,setEnvelopes]=useState<Env[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [cRes,eRes]=await Promise.all([fetch("/api/real-llm-consent?limit=100",{cache:"no-store"}),fetch("/api/approved-real-llm-invocation-envelope?limit=100",{cache:"no-store"})]); const c=await cRes.json(); const e=await eRes.json(); if(cRes.ok){ const list=Array.isArray(c.consentRequests)?c.consentRequests:[]; setRequests(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!eRes.ok) throw new Error(e?.error||"Invocation Envelopes konnten nicht geladen werden."); setEnvelopes(Array.isArray(e.invocationEnvelopes)?e.invocationEnvelopes:[]); setSummary(e.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createEnvelope(){ const res=await fetch("/api/approved-real-llm-invocation-envelope",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({consentRequestId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Envelope fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="approved-real-llm-invocation-envelope" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#ecfeff 0%,#f8fafc 100%)",borderColor:"#67e8f9"}}><h1 className="section-title">Approved Real LLM Invocation Envelope</h1><p style={{lineHeight:1.6}}>Phase 21.0 bereitet einen genehmigungsfähigen Invocation Envelope vor. Keine Tool- oder Agent-Ausführung und kein produktiver LLM-Aufruf.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Invocation Envelope vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{requests.map((req)=><option key={req.id} value={req.id}>{req.actionType || "real-llm-consent"} · {req.decision} · {req.consentScope?.approvalStatus || "unknown"} · {req.id}</option>)}</select><button className="primary-button" type="button" onClick={createEnvelope} disabled={!selected}>Approved Invocation Envelope vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Invocation Envelopes</h2>{envelopes.length===0 ? <p>Noch keine Invocation Envelopes.</p> : envelopes.map((env)=><article key={env.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{env.actionType || "approved-invocation-envelope"}</strong> <span className="chip">{env.decision}</span></div><div className="helper-text"><code>{env.id}</code> · {env.timestamp}</div><p><strong>Reason:</strong> {env.reason}</p><p><strong>Approval:</strong> {env.approvalState?.approvalStatus} · <strong>Not expired:</strong> {String(env.approvalState?.notExpired)} · <strong>Accepted for prep:</strong> {String(env.approvalState?.acceptedForEnvelopePrep)}</p><p><strong>Real LLM allowed:</strong> {String(env.realLlmCallAllowed)} · <strong>Consent:</strong> {String(env.consentRequired)} · <strong>Human approval:</strong> {String(env.humanApprovalRequired)} · <strong>LLM Call:</strong> {String(env.llmCallPerformed)} · <strong>Execution:</strong> {String(env.executionAllowed)} · <strong>Tool:</strong> {String(env.toolExecutionAllowed)} · <strong>Agent:</strong> {String(env.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(env.dryRunOnly)}</p><h3>Envelope Checks</h3><ul>{env.envelopeChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul><h3>Prompt Preview</h3><pre style={{whiteSpace:"pre-wrap"}}>{env.promptPreview}</pre></article>)}</section></div></main>;
}
