import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
export type AgentBlueprintProposalStatus = "draft" | "pending_review" | "approved" | "denied" | "activated";
export interface AgentBlueprintProposal { id:string; status:AgentBlueprintProposalStatus; agentName:string; purpose:string; source?:string; capabilityRequestId?:string; requestedCapability?:string; proposedTools:string[]; proposedPermissions:string[]; riskLevel:"low"|"medium"|"high"; requiresConsent:boolean; createdAt:string; decidedAt?:string; decisionNote?:string; metadata?:Record<string, unknown>; }
function dataDir(){ return process.env.TOOL_CONSENT_DATA_DIR || process.env.DATA_DIR || path.join(process.cwd(), "..", "data"); }
function filePath(){ return path.join(dataDir(), "agent-blueprint-proposals.json"); }
function ensureStore(){ mkdirSync(dataDir(), { recursive:true }); try{ readFileSync(filePath(), "utf8"); } catch { writeFileSync(filePath(), "[]\n", "utf8"); } }
function readProposals(): AgentBlueprintProposal[]{ ensureStore(); try{ const parsed=JSON.parse(readFileSync(filePath(), "utf8")); return Array.isArray(parsed) ? parsed.filter((entry:any)=>entry && typeof entry.id === "string") : []; } catch { return []; } }
function writeProposals(proposals: AgentBlueprintProposal[]){ ensureStore(); writeFileSync(filePath(), JSON.stringify(proposals, null, 2) + "\n", "utf8"); }
function slug(value:string){ return value.toLowerCase().replace(/[^a-z0-9Ã¤Ã¶Ã¼ÃŸ_-]+/g, "-").replace(/^-|-$/g, "").slice(0,50) || "agent-blueprint"; }
function idFor(agentName:string){ const now=new Date().toISOString(); return "blueprint-" + slug(agentName) + "-" + now.replace(/[^0-9]/g, "").slice(0,14) + "-" + Math.random().toString(36).slice(2,8); }
function normalizeList(value: unknown): string[]{ if(Array.isArray(value)) return value.filter((item): item is string => typeof item === "string").map((item)=>item.trim()).filter(Boolean); if(typeof value === "string") return value.split(",").map((item)=>item.trim()).filter(Boolean); return []; }
export function listAgentBlueprintProposals(){ const proposals=readProposals().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))); const counts=proposals.reduce((acc,p)=>{ acc.total++; acc[p.status]=(acc[p.status]||0)+1; return acc; }, { total:0, draft:0, pending_review:0, approved:0, denied:0, activated:0 } as Record<string, number>); return { ok:true, counts, proposals }; }
export function createAgentBlueprintProposal(input: { agentName:string; purpose:string; requestedCapability?:string; capabilityRequestId?:string; proposedTools?:unknown; proposedPermissions?:unknown; riskLevel?:"low"|"medium"|"high"; source?:string; metadata?:Record<string, unknown>; }){ const now=new Date().toISOString(); const agentName=input.agentName.trim(); if(!agentName) throw new Error("agentName ist erforderlich."); const purpose=input.purpose.trim(); if(!purpose) throw new Error("purpose ist erforderlich."); const proposal: AgentBlueprintProposal = { id:idFor(agentName), status:"pending_review", agentName, purpose, source: input.source || "manual-ui", capabilityRequestId: input.capabilityRequestId, requestedCapability: input.requestedCapability, proposedTools: normalizeList(input.proposedTools), proposedPermissions: normalizeList(input.proposedPermissions), riskLevel: input.riskLevel || "medium", requiresConsent:true, createdAt:now, metadata: input.metadata }; writeProposals([proposal, ...readProposals()]); return proposal; }
export function decideAgentBlueprintProposal(input: { id:string; status:"approved"|"denied"|"activated"; decisionNote?:string }){ const proposals=readProposals(); const index=proposals.findIndex((p)=>p.id===input.id); if(index<0) return null; proposals[index] = { ...proposals[index], status: input.status, decidedAt: new Date().toISOString(), decisionNote: typeof input.decisionNote === "string" ? input.decisionNote.slice(0,500) : undefined }; writeProposals(proposals); return proposals[index]; }

