export type AgentRoute = 'direct' | 'committee' | 'privacy_gate' | 'tool_required' | 'agent_builder';
export type AgentIntent = 'general' | 'live_switch' | 'internal_data' | 'committee_decision' | 'tool_required' | 'agent_builder' | 'project_next_step';
export type PrivacyDecision = 'allow_local_only' | 'require_anonymization' | 'block_external';
export type AgentLog = { id:string; createdAt:string; input:string; inputPreview:string; intent:AgentIntent; route:AgentRoute; privacyDecision:PrivacyDecision; answer:string; nextSteps:string[]; committee:{role:string;focus:string;opinion:string}[]; safetyState:{providerEnabled:false; internetEnabled:false; liveModelEnabled:false; externalSharingAllowed:false; persistedOnServer:false; persistedInBrowser:'browser_optional_local'} };
export const SECURE_MASTER_AGENT_LOG_KEY = 'cmt.secureMaster.agent.mvp.logs.v1';
export const safetyState = { providerEnabled:false, internetEnabled:false, liveModelEnabled:false, externalSharingAllowed:false, persistedOnServer:false, persistedInBrowser:'browser_optional_local' as const };
const has = (v:string, terms:string[]) => terms.some(t => v.includes(t));
export function detectIntent(input:string):AgentIntent { const v=input.toLowerCase(); if(has(v,['wetter','news','aktuell','kurs','internet','recherchier'])) return 'tool_required'; if(has(v,['kundendaten','kunde ','intern','vertraulich','geheim','angebot','kalkulation','mitarbeiter','personenbezogen'])) return 'internal_data'; if(has(v,['agent bauen','agenten bauen','spezialagent','trading agent','immobilien agent','bauleiter entlasten'])) return 'agent_builder'; if(has(v,['live schalten','aktivieren','provider','ki-modell','modell anschließen','modell anschliessen'])) return 'live_switch'; if(has(v,['soll ich','sollen wir','entscheidung','priorisieren','strategie','risiko','gremium'])) return 'committee_decision'; if(has(v,['nächster schritt','naechster schritt','roadmap','was als nächstes','weiterbauen','verbessern'])) return 'project_next_step'; return 'general'; }
export function routeIntent(intent:AgentIntent):AgentRoute { if(intent==='internal_data') return 'privacy_gate'; if(intent==='tool_required') return 'tool_required'; if(intent==='agent_builder') return 'agent_builder'; if(intent==='committee_decision'||intent==='live_switch'||intent==='project_next_step') return 'committee'; return 'direct'; }
export function decidePrivacy(input:string):PrivacyDecision { const v=input.toLowerCase(); if(has(v,['geheim','passwort','api key','token','personenbezogen'])) return 'block_external'; if(has(v,['kunde','kundendaten','angebot','kalkulation','mitarbeiter','intern','vertraulich'])) return 'require_anonymization'; return 'allow_local_only'; }
function committee(route:AgentRoute){ if(!['committee','agent_builder','privacy_gate'].includes(route)) return []; return [ {role:'Visionär',focus:'Chance und Zielbild',opinion:'Fokus auf eine zentrale Arbeitsseite statt weiterer Statusseiten.'}, {role:'Skeptiker',focus:'Risiken und blinde Flecken',opinion:'Erst Eingabe, Antwort, Datenschutzprüfung, Log und Verlauf stabil machen.'}, {role:'Umsetzer',focus:'Nächster Schritt',opinion:'Frage eingeben, lokal prüfen, Antwort anzeigen, Browser-Log speichern.'}, {role:'Datenschutz & Risiko',focus:'Interne Daten',opinion:'Kein Provider, kein Internet, keine externe Weitergabe ohne spätere Freigabe.'}, {role:'Wirtschaftlichkeit & Praxisnutzen',focus:'Alltagstauglichkeit',opinion:'Der Agent wird wertvoll, wenn er echte Fragen schnell sortiert und nachvollziehbar protokolliert.'} ]; }
function answer(input:string,intent:AgentIntent,route:AgentRoute,privacy:PrivacyDecision){ if(route==='tool_required') return 'Diese Frage braucht wahrscheinlich Internet, aktuelle Daten oder ein externes Tool. Aktuell bleibt der Secure Master lokal: kein Internet, kein Provider, kein Live-Modell.'; if(route==='privacy_gate') return privacy==='block_external' ? 'Ich erkenne sensible/geheime Inhalte. Externe Weitergabe ist blockiert. Nur lokal bewerten.' : 'Ich erkenne interne/geschäftliche Daten. Lokal bearbeiten oder später anonymisieren und Freigabe einholen.'; if(route==='agent_builder') return 'Das klingt nach einem Spezialagenten. Nächster Schritt: Agentenprofil mit Ziel, Eingaben, Datenquellen, Grenzen, Datenschutzregeln und Testfragen erstellen.'; if(intent==='live_switch') return 'Noch nicht live schalten. Erst lokalen Master-Agent-Flow stabilisieren, danach Provider-Gate und Live-Schalter kontrolliert aktivieren.'; if(route==='committee') return 'Diese Frage eignet sich für das 5er-Gremium. Empfehlung: Chance, Risiko, Umsetzung, Datenschutz und wirtschaftlichen Nutzen gemeinsam prüfen.'; return 'Lokale Antwort: Ich ordne diese Frage im sicheren Trockenlauf ein. Es wird nichts extern gesendet.'; }
function steps(route:AgentRoute){ if(route==='tool_required') return ['Toolbedarf markieren','Datenquelle definieren','später Web/Provider nur per Freigabe aktivieren']; if(route==='privacy_gate') return ['nur lokal verarbeiten','interne Begriffe prüfen','Anonymisierung vorbereiten']; if(route==='agent_builder') return ['Spezialagenten-Ziel definieren','Eingaben/Ausgaben festlegen','Datenschutzgrenzen setzen']; if(route==='committee') return ['Gremium prüfen lassen','Risiken notieren','Entscheidungsvorschlag ableiten']; return ['lokal beantworten','bei Unsicherheit Gremium einschalten','Antwort im Browser-Log speichern']; }
export function runSecureMasterLocalAgent(input:string):AgentLog { const intent=detectIntent(input); const route=routeIntent(intent); const privacyDecision=decidePrivacy(input); return { id:'agent_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8), createdAt:new Date().toISOString(), input, inputPreview:input.trim().slice(0,160), intent, route, privacyDecision, answer:answer(input,intent,route,privacyDecision), nextSteps:steps(route), committee:committee(route), safetyState}; }
