import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
export type ControlledAgentStatus = "registered" | "disabled" | "test_mode" | "active";
export interface ControlledAgentRegistryEntry { id:string; status:ControlledAgentStatus; agentName:string; purpose:string; source?:string; blueprintProposalId?:string; requestedCapability?:string; allowedTools:string[]; permissions:string[]; riskLevel:"low"|"medium"|"high"; requiresConsent:boolean; createdAt:string; updatedAt:string; activationNote?:string; metadata?:Record<string, unknown>; }
function dataDir(){ return process.env.TOOL_CONSENT_DATA_DIR || process.env.DATA_DIR || path.join(process.cwd(), "..", "data"); }
function filePath(){ return path.join(dataDir(), "controlled-agent-registry.json"); }
async function ensureStore(){ await mkdir(dataDir(), { recursive:true }); try{ await readFile(filePath(), "utf8"); } catch { await writeFile(filePath(), "[]\n", "utf8"); } }
async function readEntries(): Promise<ControlledAgentRegistryEntry[]>{ await ensureStore(); try{ const parsed=JSON.parse(await readFile(filePath(), "utf8")); return Array.isArray(parsed) ? parsed.filter((entry:any)=>entry && typeof entry.id === "string") : []; } catch { return []; } }
async function writeEntries(entries: ControlledAgentRegistryEntry[]){ await ensureStore(); await writeFile(filePath(), JSON.stringify(entries, null, 2) + "\n", "utf8"); }
function slug(value:string){ return value.toLowerCase().replace(/[^a-z0-9äöüß_-]+/g, "-").replace(/^-|-$/g, "").slice(0,55) || "controlled-agent"; }
function idFor(agentName:string){ const now=new Date().toISOString(); return "agent-" + slug(agentName) + "-" + now.replace(/[^0-9]/g, "").slice(0,14); }
function normalizeList(value: unknown): string[]{ if(Array.isArray(value)) return value.filter((item): item is string => typeof item === "string").map((item)=>item.trim()).filter(Boolean); if(typeof value === "string") return value.split(",").map((item)=>item.trim()).filter(Boolean); return []; }
export async function listControlledAgents(){ const entries=(await readEntries()).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))); const counts=entries.reduce((acc,e)=>{ acc.total++; acc[e.status]=(acc[e.status]||0)+1; return acc; }, { total:0, registered:0, disabled:0, test_mode:0, active:0 } as Record<string, number>); return { ok:true, counts, entries }; }
export async function registerControlledAgent(input: { agentName:string; purpose:string; blueprintProposalId?:string; requestedCapability?:string; allowedTools?:unknown; permissions?:unknown; riskLevel?:"low"|"medium"|"high"; activationNote?:string; metadata?:Record<string, unknown>; }){ const now=new Date().toISOString(); const agentName=input.agentName.trim(); if(!agentName) throw new Error("agentName ist erforderlich."); const purpose=input.purpose.trim(); if(!purpose) throw new Error("purpose ist erforderlich."); const entry: ControlledAgentRegistryEntry = { id:idFor(agentName), status:"test_mode", agentName, purpose, source:"agent-blueprint", blueprintProposalId: input.blueprintProposalId, requestedCapability: input.requestedCapability, allowedTools: normalizeList(input.allowedTools), permissions: normalizeList(input.permissions), riskLevel: input.riskLevel || "medium", requiresConsent:true, createdAt:now, updatedAt:now, activationNote: input.activationNote || "Registriert in Test Mode. Keine automatische Ausführung.", metadata: input.metadata }; await writeEntries([entry, ...(await readEntries())]); return entry; }
export async function updateControlledAgentStatus(input: { id:string; status:ControlledAgentStatus; activationNote?:string }){ const entries=await readEntries(); const index=entries.findIndex((entry)=>entry.id===input.id); if(index<0) return null; entries[index] = { ...entries[index], status: input.status, updatedAt: new Date().toISOString(), activationNote: typeof input.activationNote === "string" ? input.activationNote.slice(0,500) : entries[index].activationNote }; await writeEntries(entries); return entries[index]; }
