import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
export type CapabilityRequestStatus = "pending" | "approved" | "denied" | "implemented" | "expired";
export interface CapabilityRequest { id: string; status: CapabilityRequestStatus; requestedCapability: string; reason?: string; userInputPreview?: string; riskLevel?: "low" | "medium" | "high"; source?: string; requestedAt: string; decidedAt?: string; decisionNote?: string; metadata?: Record<string, unknown>; }
function dataDir(){ return process.env.TOOL_CONSENT_DATA_DIR || process.env.DATA_DIR || path.join(process.cwd(), "..", "data"); }
function filePath(){ return path.join(dataDir(), "tool-capability-requests.json"); }
function ensureStore(){ mkdirSync(dataDir(), { recursive: true }); try { readFileSync(filePath(), "utf8"); } catch { writeFileSync(filePath(), "[]\n", "utf8"); } }
function sanitize(value: unknown, max=240){ return typeof value === "string" ? value.replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi, "[redacted-email]").replace(/(api[_-]?key|token|secret|password)\s*[:=]\s*[^\s,;]+/gi, "$1=[redacted]").slice(0,max) : undefined; }
function readRequests(): CapabilityRequest[]{ ensureStore(); try { const parsed = JSON.parse(readFileSync(filePath(), "utf8")); return Array.isArray(parsed) ? parsed.filter((entry: any) => entry && typeof entry.id === "string") : []; } catch { return []; } }
function writeRequests(requests: CapabilityRequest[]){ ensureStore(); writeFileSync(filePath(), JSON.stringify(requests, null, 2) + "\n", "utf8"); }
function idFor(capability: string){ const now = new Date().toISOString(); const slug = capability.toLowerCase().replace(/[^a-z0-9Ã¤Ã¶Ã¼ÃŸ_-]+/g, "-").replace(/^-|-$/g, "").slice(0,48) || "capability"; return `capability-${slug}-${now.replace(/[^0-9]/g, "").slice(0,14)}-${Math.random().toString(36).slice(2,8)}`; }
export function listCapabilityRequests(){ const requests = readRequests().sort((a,b)=>String(b.requestedAt).localeCompare(String(a.requestedAt))); const counts = requests.reduce((acc, r) => { acc.total++; acc[r.status] = (acc[r.status] || 0) + 1; return acc; }, { total: 0, pending: 0, approved: 0, denied: 0, implemented: 0, expired: 0 } as Record<string, number>); return { ok: true, counts, requests }; }
export function createCapabilityRequest(input: { requestedCapability: string; reason?: string; userInputPreview?: string; riskLevel?: "low"|"medium"|"high"; metadata?: Record<string, unknown>; }){ const now = new Date().toISOString(); const requestedCapability = input.requestedCapability.trim(); if(!requestedCapability) throw new Error("requestedCapability ist erforderlich."); const request: CapabilityRequest = { id: idFor(requestedCapability), status: "pending", requestedCapability, reason: sanitize(input.reason, 500), userInputPreview: sanitize(input.userInputPreview), riskLevel: input.riskLevel || "medium", source: "manual-ui", requestedAt: now, metadata: input.metadata }; writeRequests([request, ...readRequests()]); return request; }
export function decideCapabilityRequest(input: { id: string; status: "approved"|"denied"|"implemented"; decisionNote?: string }){ const requests = readRequests(); const index = requests.findIndex((r)=>r.id===input.id); if(index < 0) return null; requests[index] = { ...requests[index], status: input.status, decidedAt: new Date().toISOString(), decisionNote: sanitize(input.decisionNote, 500) }; writeRequests(requests); return requests[index]; }

