"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";
type Receipt = { id: string; decision: string; timestamp: string; receiptMode: string };
type Ack = { id: string; timestamp: string; decision: string; reason: string; acknowledgementMode: string; providerDispatchHumanApprovalTokenIssuanceReceiptAcknowledgementRecorded: boolean; humanApprovalTokenIssuanceReceiptAcknowledgementPrepared: boolean; humanApprovalTokenIssued: boolean; humanApprovalTokenActivated: boolean; humanApprovalTokenConsumed: boolean; approvalCandidateApproved: boolean; approvalCandidateExecuted: boolean; networkCallPerformed: boolean; providerExecutionAllowed: boolean; llmCallPerformed: boolean; dryRunOnly: boolean };
export default function ProviderDispatchHumanApprovalTokenIssuanceReceiptAcknowledgementPage() {
  const [receipts, setReceipts] = useState<Receipt[]>([]); const [acks, setAcks] = useState<Ack[]>([]); const [summary, setSummary] = useState<unknown>(null); const [selected, setSelected] = useState(""); const [error, setError] = useState<string | null>(null);
  async function load() { setError(null); try { const [rRes, aRes] = await Promise.all([fetch("/api/provider-dispatch-human-approval-token-issuance-receipt?limit=100", { cache: "no-store" }), fetch("/api/provider-dispatch-human-approval-token-issuance-receipt-acknowledgement?limit=100", { cache: "no-store" })]); const r = await rRes.json(); const a = await aRes.json(); if (rRes.ok) { const list = Array.isArray(r.providerDispatchHumanApprovalTokenIssuanceReceipts) ? r.providerDispatchHumanApprovalTokenIssuanceReceipts : []; setReceipts(list); if (!selected && list[0]?.id) setSelected(list[0].id); } if (!aRes.ok) throw new Error(a?.error || "Acknowledgements konnten nicht geladen werden."); setAcks(Array.isArray(a.providerDispatchHumanApprovalTokenIssuanceReceiptAcknowledgements) ? a.providerDispatchHumanApprovalTokenIssuanceReceiptAcknowledgements : []); setSummary(a.summary || null); } catch (err) { setError(err instanceof Error ? err.message : "Unbekannter Fehler"); } }
  useEffect(() => { load(); }, []);
  async function createAcknowledgement() { const res = await fetch("/api/provider-dispatch-human-approval-token-issuance-receipt-acknowledgement", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ providerDispatchHumanApprovalTokenIssuanceReceiptId: selected }) }); if (!res.ok) { const p = await res.json(); setError(p?.error || "Acknowledgement fehlgeschlagen"); } await load(); }
  return <main className="page-wrap"><UnifiedNavigation active="provider-dispatch-human-approval-token-issuance-receipt-acknowledgement" /><div className="page-shell"><section className="hero-card"><h1 className="section-title">Provider Dispatch Human Approval Token Issuance Receipt Acknowledgement</h1><p style={{ lineHeight: 1.6 }}>Phase 48.0 schreibt ein metadata-only Acknowledgement zur Issuance Receipt Chain. Das Acknowledgement ist acknowledgement-only und review-only. Der Token bleibt nicht issued, nicht aktiviert und nicht konsumiert. Kein Provider Dispatch und kein Provider-/Netzwerk-Aufruf.</p></section>{error ? <section className="panel-card" style={{ borderColor: "#fecaca", background: "#fef2f2" }}>{error}</section> : null}<section className="panel-card"><h2>Acknowledgement schreiben</h2><select className="text-input" value={selected} onChange={(ev) => setSelected(ev.target.value)}>{receipts.map((item) => <option key={item.id} value={item.id}>{item.receiptMode} · {item.decision} · {item.id}</option>)}</select><button className="primary-button" type="button" onClick={createAcknowledgement} disabled={!selected}>Human Approval Token Issuance Receipt Acknowledgement schreiben</button></section><section className="panel-card"><h2>Summary</h2><pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Acknowledgements</h2>{acks.length === 0 ? <p>Noch keine Acknowledgements.</p> : acks.map((item) => <article key={item.id} style={{ borderTop: "1px solid #e5e7eb", padding: "12px 0" }}><div><strong>{item.acknowledgementMode}</strong> <span className="chip">{item.decision}</span></div><div className="helper-text"><code>{item.id}</code> · {item.timestamp}</div><p><strong>Reason:</strong> {item.reason}</p><p><strong>Acknowledgement recorded:</strong> {String(item.providerDispatchHumanApprovalTokenIssuanceReceiptAcknowledgementRecorded)} · <strong>Prepared:</strong> {String(item.humanApprovalTokenIssuanceReceiptAcknowledgementPrepared)} · <strong>Issued:</strong> {String(item.humanApprovalTokenIssued)} · <strong>Activated:</strong> {String(item.humanApprovalTokenActivated)} · <strong>Consumed:</strong> {String(item.humanApprovalTokenConsumed)}</p><p><strong>Approved:</strong> {String(item.approvalCandidateApproved)} · <strong>Executed:</strong> {String(item.approvalCandidateExecuted)} · <strong>Network:</strong> {String(item.networkCallPerformed)} · <strong>Provider execution:</strong> {String(item.providerExecutionAllowed)} · <strong>LLM:</strong> {String(item.llmCallPerformed)} · <strong>Dry-run:</strong> {String(item.dryRunOnly)}</p></article>)}</section></div></main>;
}
