"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Rec={id:string;title:string;decision:string;actionType?:string};
type Sim={id:string;timestamp:string;decision:string;actionType?:string;reason:string;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;llmRoutingPrepOnly:boolean;policyChecks:Array<{name:string;passed:boolean;reason:string}>};
export default function MasterPlannerPolicyPage(){
 const [recs,setRecs]=useState<Rec[]>([]); const [sims,setSims]=useState<Sim[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [rRes,sRes]=await Promise.all([fetch("/api/master-planner?limit=100",{cache:"no-store"}),fetch("/api/master-planner-policy?limit=100",{cache:"no-store"})]); const r=await rRes.json(); const s=await sRes.json(); if(rRes.ok){ const list=Array.isArray(r.recommendations)?r.recommendations:[]; setRecs(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!sRes.ok) throw new Error(s?.error||"Planner Policy Simulations konnten nicht geladen werden."); setSims(Array.isArray(s.simulations)?s.simulations:[]); setSummary(s.summary||null); } catch(e){ setError(e instanceof Error?e.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function simulate(){ const res=await fetch("/api/master-planner-policy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recommendationId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Simulation fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="master-planner-policy" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#fdf2f8 0%,#f8fafc 100%)",borderColor:"#f9a8d4"}}><h1 className="section-title">Master Planner Policy</h1><p style={{lineHeight:1.6}}>Phase 16.1 simuliert Policy Checks für Planner Recommendations und schreibt Audit Events. Keine echte Ausführung.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Policy Simulation erstellen</h2><select className="text-input" value={selected} onChange={(e)=>setSelected(e.target.value)}>{recs.map((rec)=><option key={rec.id} value={rec.id}>{rec.title} · {rec.decision} · {rec.id}</option>)}</select><button className="primary-button" type="button" onClick={simulate} disabled={!selected}>Planner Policy simulieren</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Policy Simulations</h2>{sims.length===0 ? <p>Noch keine Planner Policy Simulations.</p> : sims.map((sim)=><article key={sim.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{sim.actionType || "planner"}</strong> <span className="chip">{sim.decision}</span></div><div className="helper-text"><code>{sim.id}</code> · {sim.timestamp}</div><p><strong>Reason:</strong> {sim.reason}</p><p><strong>Execution:</strong> {String(sim.executionAllowed)} · <strong>Tool:</strong> {String(sim.toolExecutionAllowed)} · <strong>Agent:</strong> {String(sim.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(sim.dryRunOnly)} · <strong>LLM Routing Prep:</strong> {String(sim.llmRoutingPrepOnly)}</p><ul>{sim.policyChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul></article>)}</section></div></main>;
}
