"use client";
import { useEffect, useState } from "react";
import { UnifiedNavigation } from "../../components/UnifiedNavigation";

type Gate={id:string;decision:string;actionType?:string;timestamp:string};
type Consent={id:string;timestamp:string;decision:string;actionType?:string;reason:string;promptPreview:string;realLlmCallAllowed:boolean;llmCallPerformed:boolean;consentRequired:boolean;humanApprovalRequired:boolean;executionAllowed:boolean;toolExecutionAllowed:boolean;agentExecutionAllowed:boolean;dryRunOnly:boolean;consentChecks:Array<{name:string;passed:boolean;reason:string}>;consentScope:{approvalStatus:string;expiresAt:string}};
export default function RealLlmInvocationConsentPage(){
 const [gates,setGates]=useState<Gate[]>([]); const [requests,setRequests]=useState<Consent[]>([]); const [summary,setSummary]=useState<any>(null); const [selected,setSelected]=useState(""); const [error,setError]=useState<string|null>(null);
 async function load(){ setError(null); try{ const [gRes,cRes]=await Promise.all([fetch("/api/real-llm-call-gate?limit=100",{cache:"no-store"}),fetch("/api/real-llm-consent?limit=100",{cache:"no-store"})]); const g=await gRes.json(); const c=await cRes.json(); if(gRes.ok){ const list=Array.isArray(g.gates)?g.gates:[]; setGates(list); if(!selected && list[0]?.id) setSelected(list[0].id); } if(!cRes.ok) throw new Error(c?.error||"Real LLM Consent Requests konnten nicht geladen werden."); setRequests(Array.isArray(c.consentRequests)?c.consentRequests:[]); setSummary(c.summary||null); } catch(err){ setError(err instanceof Error?err.message:"Unbekannter Fehler"); } }
 useEffect(()=>{ load(); },[]);
 async function createConsent(){ const res=await fetch("/api/real-llm-consent",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gateId:selected})}); if(!res.ok){ const p=await res.json(); setError(p?.error||"Consent Request fehlgeschlagen"); } await load(); }
 return <main className="page-wrap"><UnifiedNavigation active="real-llm-consent" /><div className="page-shell"><section className="hero-card" style={{background:"linear-gradient(135deg,#eff6ff 0%,#f8fafc 100%)",borderColor:"#93c5fd"}}><h1 className="section-title">Real LLM Invocation Consent</h1><p style={{lineHeight:1.6}}>Phase 20.0 bereitet ein ausdrückliches Human-Approval-Gate für spätere echte LLM-Aufrufe vor. Kein produktiver LLM-Aufruf ohne explizite Freigabe.</p></section>{error ? <section className="panel-card" style={{borderColor:"#fecaca",background:"#fef2f2"}}>{error}</section> : null}<section className="panel-card"><h2>Consent Request vorbereiten</h2><select className="text-input" value={selected} onChange={(ev)=>setSelected(ev.target.value)}>{gates.map((gate)=><option key={gate.id} value={gate.id}>{gate.actionType || "real-llm-gate"} · {gate.decision} · {gate.id}</option>)}</select><button className="primary-button" type="button" onClick={createConsent} disabled={!selected}>Real LLM Consent Request vorbereiten</button></section><section className="panel-card"><h2>Summary</h2><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(summary ?? {}, null, 2)}</pre></section><section className="panel-card"><h2>Consent Requests</h2>{requests.length===0 ? <p>Noch keine Consent Requests.</p> : requests.map((req)=><article key={req.id} style={{borderTop:"1px solid #e5e7eb",padding:"12px 0"}}><div><strong>{req.actionType || "real-llm-consent"}</strong> <span className="chip">{req.decision}</span></div><div className="helper-text"><code>{req.id}</code> · {req.timestamp}</div><p><strong>Reason:</strong> {req.reason}</p><p><strong>Approval:</strong> {req.consentScope?.approvalStatus} · <strong>Expires:</strong> {req.consentScope?.expiresAt}</p><p><strong>Real LLM allowed:</strong> {String(req.realLlmCallAllowed)} · <strong>Consent:</strong> {String(req.consentRequired)} · <strong>Human approval:</strong> {String(req.humanApprovalRequired)} · <strong>LLM Call:</strong> {String(req.llmCallPerformed)} · <strong>Execution:</strong> {String(req.executionAllowed)} · <strong>Tool:</strong> {String(req.toolExecutionAllowed)} · <strong>Agent:</strong> {String(req.agentExecutionAllowed)} · <strong>Dry-run:</strong> {String(req.dryRunOnly)}</p><h3>Consent Checks</h3><ul>{req.consentChecks?.map((check)=><li key={check.name}><strong>{check.name}:</strong> {String(check.passed)} – {check.reason}</li>)}</ul><h3>Prompt Preview</h3><pre style={{whiteSpace:"pre-wrap"}}>{req.promptPreview}</pre></article>)}</section></div></main>;
}
